/* AWEP2PAWE — static-only P2P runtime. No application backend, no cloud storage. */
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const DB='awep2pawe',VER=3;
const S={id:localStorage.getItem('awe_identity')||'',name:localStorage.getItem('awe_name')||'AWE User',theme:localStorage.getItem('awe_theme')||'dark',resources:JSON.parse(localStorage.getItem('awe_resources')||'[]'),contacts:JSON.parse(localStorage.getItem('awe_contacts')||'[]'),rooms:JSON.parse(localStorage.getItem('awe_rooms')||'[]'),type:'fid',peer:null,dc:null,peerId:null,ice:[]};
let localKeys=null,callPC=null,localStream=null;
const te=new TextEncoder(),td=new TextDecoder();
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))),unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const toast=t=>{let x=$('#toast');if(!x){x=document.createElement('div');x.id='toast';x.className='toast';document.body.append(x)}x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),2600)};
const bytesHex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha(b){return bytesHex(await crypto.subtle.digest('SHA-256',b))}
async function db(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;for(const n of ['files','messages','rooms'])if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id',autoIncrement:n==='messages'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function put(store,v){const d=await db();return new Promise((ok,no)=>{const t=d.transaction(store,'readwrite');t.objectStore(store).put(v);t.oncomplete=ok;t.onerror=()=>no(t.error)})}
async function get(store,key){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(store,'readonly').objectStore(store).get(key);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function keyFromPassword(p,salt){const base=await crypto.subtle.importKey('raw',te.encode(p),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function makeIdentity(){const kp=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);const pub=await crypto.subtle.exportKey('raw',kp.publicKey);S.id='awe1:'+await sha(pub);localStorage.setItem('awe_identity',S.id);localStorage.setItem('awe_pub',b64(pub));localStorage.setItem('awe_priv',JSON.stringify(await crypto.subtle.exportKey('jwk',kp.privateKey)));localKeys=kp;return kp}
async function loadIdentity(){if(!S.id)return makeIdentity();try{const priv=JSON.parse(localStorage.getItem('awe_priv'));const pub=unb64(localStorage.getItem('awe_pub'));localKeys={privateKey:await crypto.subtle.importKey('jwk',priv,{name:'ECDSA',namedCurve:'P-256'},true,['sign']),publicKey:await crypto.subtle.importKey('raw',pub,{name:'ECDSA',namedCurve:'P-256'},true,['verify'])}}catch{await makeIdentity()}}
function save(){localStorage.setItem('awe_name',S.name);localStorage.setItem('awe_theme',S.theme);localStorage.setItem('awe_resources',JSON.stringify(S.resources));localStorage.setItem('awe_contacts',JSON.stringify(S.contacts));localStorage.setItem('awe_rooms',JSON.stringify(S.rooms))}
function formatBytes(n){const u=['B','KB','MB','GB','TB'];let i=0,x=n||0;while(x>=1024&&i<4){x/=1024;i++}return `${x.toFixed(i?1:0)} ${u[i]}`}
function copy(t){navigator.clipboard?.writeText(t).then(()=>toast('Պատճենվեց')).catch(()=>toast(t))}
function msg(text,kind='outgoing',meta='հիմա ✓'){const m=document.createElement('div');m.className='message '+kind;m.innerHTML=`<p>${esc(text)}</p><time>${esc(meta)}</time>`;$('#messages').append(m);$('#messages').scrollTop=1e9}
function status(t){const x=$('#p2p-status');if(x)x.textContent=t}
function nav(){ $$('.nav-item').forEach(b=>b.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(x=>x.classList.remove('active-view'));$('#view-'+b.dataset.view)?.classList.add('active-view')}) }
function chats(){ $$('.chat-row').forEach(r=>r.onclick=()=>{$$('.chat-row').forEach(x=>x.classList.remove('selected'));r.classList.add('selected');$('#conversation-name').textContent=r.dataset.chat}) }
function messaging(){ $('#message-form').onsubmit=async e=>{e.preventDefault();const i=$('#message-input'),t=i.value.trim();if(!t)return;i.value='';msg(t);await put('messages',{room:S.peerId||'local',from:S.id,text:t,time:Date.now()});send({kind:'chat',text:t,from:S.id})} }
function injectNetworkUI(){
 const c=$('#view-contacts');if(c&&!$('#uid-panel')){const p=document.createElement('section');p.id='uid-panel';p.className='settings-panel';p.innerHTML=`<div class="setting"><div><strong>AWE ID</strong><small>Քո ինքնությունը ստեղծվում է սարքում և գաղտնի բանալին դուրս չի գալիս դրանից։</small><code id="my-id"></code></div><button class="ghost" id="copy-id">Կիսել ID</button></div><div class="setting"><div style="width:100%"><strong>Միանալ AWE ID-ով</strong><small>UID-ը ինքնին ինքնության հասցե է։ Առանց որևէ rendezvous/backend ծառայության այն չի կարող ինտերնետով հայտնաբերել անջատված peer-ին, ուստի առաջին կապի համար օգտագործվում է մեկանգամյա կապի փաթեթը։</small><input id="uid-input" placeholder="awe1:…" style="width:100%;margin-top:8px"><textarea id="invite-input" rows="5" placeholder="Կապի փաթեթը այստեղ…" style="width:100%;margin-top:8px"></textarea><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:8px"><button class="primary" id="connect-uid">Միանալ</button><button class="ghost" id="make-invite">Ստեղծել կապի փաթեթ</button></div></div></div>`;c.append(p)}
 const calls=$('#view-calls');if(calls&&!$('#call-panel')){const p=document.createElement('section');p.id='call-panel';p.className='settings-panel';p.innerHTML=`<div class="setting"><div><strong>Ուղիղ ձայն / տեսազանգ</strong><small>Աշխատում է արդեն հաստատված P2P peer կապի վրայով։</small></div><div style="display:flex;gap:8px"><button class="primary" id="voice-call">🎙️</button><button class="primary" id="video-call">📹</button><button class="ghost" id="hangup">✕</button></div></div><div id="media-box" style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px"></div>`;calls.append(p)}
 const chatHead=$('.conversation-head');if(chatHead&&!$('#call-head-actions')){const a=document.createElement('div');a.id='call-head-actions';a.className='head-actions';a.innerHTML='<button class="icon-btn" id="quick-voice">🎙️</button><button class="icon-btn" id="quick-video">📹</button>';chatHead.append(a)}
 $('#my-id').textContent=S.id;$('#copy-id').onclick=()=>copy(S.id);$('#make-invite').onclick=makeOffer;$('#connect-uid').onclick=()=>{const raw=$('#invite-input').value.trim();if(raw)acceptInvite(raw);else toast('Առաջին կապի փաթեթը պետք է տեղադրել')};$('#voice-call').onclick=()=>startCall(false);$('#video-call').onclick=()=>startCall(true);$('#quick-voice').onclick=()=>startCall(false);$('#quick-video').onclick=()=>startCall(true);$('#hangup').onclick=hangup;
}
function newPC(){if(S.peer){try{S.peer.close()}catch{}}S.peer=new RTCPeerConnection({iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}]});S.peer.onconnectionstatechange=()=>status('Կապ՝ '+S.peer.connectionState);S.peer.ondatachannel=e=>attach(e.channel);return S.peer}
function attach(ch){S.dc=ch;ch.binaryType='arraybuffer';ch.onopen=()=>{status('P2P կապը ակտիվ է');send({kind:'hello',uid:S.id,name:S.name,pub:localStorage.getItem('awe_pub')})};ch.onclose=()=>status('P2P կապը փակ է');ch.onmessage=onData}
function waitIce(pc){if(pc.iceGatheringState==='complete')return Promise.resolve();return new Promise(r=>{const f=()=>{if(pc.iceGatheringState==='complete'){pc.removeEventListener('icegatheringstatechange',f);r()}};pc.addEventListener('icegatheringstatechange',f);setTimeout(r,7000)})}
async function makeOffer(){const pc=newPC();attach(pc.createDataChannel('awe'));const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);const packet=btoa(JSON.stringify({v:1,uid:S.id,description:pc.localDescription}));$('#invite-input').value=packet;$('#uid-input').value=S.id;copy(packet);toast('Կապի փաթեթը պատրաստ է')}
async function acceptInvite(packet){try{const x=JSON.parse(atob(packet));if(!x.description)throw Error();const pc=newPC();await pc.setRemoteDescription(x.description);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await waitIce(pc);$('#invite-input').value=btoa(JSON.stringify({v:1,uid:S.id,reply:true,description:pc.localDescription}));$('#uid-input').value=x.uid||'';toast('Պատասխանը պատրաստ է․ ուղարկիր նույն մարդուն')}catch{toast('Կապի փաթեթը սխալ է')}}
async function acceptAnswer(packet){try{const x=JSON.parse(atob(packet));await S.peer.setRemoteDescription(x.description);toast('Կապը հաստատվում է')}catch{toast('Պատասխանը սխալ է')}}
function send(o){if(S.dc?.readyState==='open')S.dc.send(JSON.stringify(o))}
async function onData(e){if(typeof e.data!=='string')return;let m;try{m=JSON.parse(e.data)}catch{return}if(m.kind==='hello'){S.peerId=m.uid;addContact(m.uid,m.name||'AWE User');status(`Միացված՝ ${m.name||m.uid}`);return}if(m.kind==='chat'){msg(m.text,'incoming','P2P');await put('messages',{room:m.from||S.peerId,from:m.from,text:m.text,time:Date.now()});return}if(m.kind==='resource-request'){return serve(m)}if(m.kind==='resource-meta'){window.__rx={m,b:[]};return}if(m.kind==='resource-chunk'){window.__rx?.b.push(unb64(m.data));return}if(m.kind==='resource-end'){return finishRx()}if(m.kind==='room-invite'){acceptRoom(m.room);return}if(m.kind==='call-offer'){return answerCall(m)}if(m.kind==='call-answer'){if(callPC)await callPC.setRemoteDescription(m.description);return}if(m.kind==='call-candidate'&&callPC){try{await callPC.addIceCandidate(m.candidate)}catch{}}}
function addContact(id,name){if(!id||id===S.id)return;if(!S.contacts.some(x=>x.id===id)){S.contacts.unshift({id,name,added:Date.now()});save();renderContacts()} }
function renderContacts(){const grid=$('#view-contacts .cards-grid');if(!grid)return;grid.innerHTML=S.contacts.map(c=>`<article class="contact-card"><span class="avatar blue">${esc((c.name||'A')[0])}</span><div><strong>${esc(c.name||'AWE User')}</strong><code>${esc(c.id)}</code></div><span class="online-dot"></span></article>`).join('')||'<article class="contact-card"><div><strong>Դեռ կոնտակտ չկա</strong><small>Կիսիր AWE ID-ը կամ կապի փաթեթը</small></div></article>'}
function acceptRoom(room){if(!room?.id)return;S.rooms=S.rooms.filter(x=>x.id!==room.id);S.rooms.unshift({...room,joined:Date.now()});save();toast(`${room.kind==='channel'?'Ալիք':'Խումբ'}՝ ${room.name}`);msg(`🔗 Միացա ${room.kind==='channel'?'ալիքին':'խմբին'} «${room.name}»`,'incoming','P2P')}
function injectRooms(){const p=document.createElement('section');p.className='settings-panel';p.innerHTML=`<div class="setting"><div><strong>Խմբեր և ալիքներ</strong><small>Հրավերը փոխանցվում է միայն P2P կապով և անդամակցությունը պահվում է քո սարքում։</small></div><div><button class="primary" id="new-group">＋ Խումբ</button> <button class="ghost" id="new-channel">＋ Ալիք</button></div></div>`;$('#view-contacts')?.append(p);$('#new-group').onclick=()=>createRoom('group');$('#new-channel').onclick=()=>createRoom('channel')}
function createRoom(kind){const name=prompt(kind==='channel'?'Ալիքի անունը':'Խմբի անունը');if(!name)return;const room={id:'room:'+crypto.randomUUID(),kind,name,owner:S.id};S.rooms.unshift(room);save();if(S.dc?.readyState==='open')send({kind:'room-invite',room});toast(`${kind==='channel'?'Ալիք':'Խումբ'} ստեղծվեց`)}
async function serve(m){const r=await get('files',m.id);if(!r){send({kind:'error',message:'FID/PFID հասանելի չէ այս պահին'});return}send({kind:'resource-meta',id:r.id,name:r.name,mime:r.mime,size:r.size,hash:r.hash,protected:!!r.protected,salt:r.salt,iv:r.iv});const u=new Uint8Array(r.blob);for(let i=0;i<u.length;i+=49152){while(S.dc.bufferedAmount>524288)await new Promise(r=>setTimeout(r,8));send({kind:'resource-chunk',data:b64(u.slice(i,i+49152))})}send({kind:'resource-end',hash:r.hash})}
async function finishRx(){const r=window.__rx;if(!r)return;const all=new Uint8Array(r.b.reduce((n,x)=>n+x.length,0));let o=0;for(const x of r.b){all.set(x,o);o+=x.length}if(await sha(all)!==r.m.hash){toast('Ֆայլի integrity ստուգումը ձախողվեց');return}let data=all;if(r.m.protected){const p=prompt('PFID գաղտնաբառը');if(!p)return;try{const k=await keyFromPassword(p,unb64(r.m.salt));data=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(r.m.iv)},k,all))}catch{toast('Գաղտնաբառը սխալ է');return}}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:r.m.mime}));a.download=r.m.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);window.__rx=null;toast('Ներբեռնումը ավարտվեց և ստուգվեց')}
async function createResource(file,privateMode=false){const raw=new Uint8Array(await file.arrayBuffer()),hash=await sha(raw);let rec={id:(privateMode?'pfid':'fid')+':'+hash.slice(0,40),type:privateMode?'pfid':'fid',name:file.name,size:file.size,mime:file.type||'application/octet-stream',hash,owner:S.id,created:Date.now(),protected:privateMode};let data=raw;if(privateMode){const p=prompt('PFID գաղտնաբառը՝ առնվազն 8 նիշ');if(!p||p.length<8)return toast('Չեղարկվեց');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.randomValues?crypto.randomValues(new Uint8Array(12)):crypto.getRandomValues(new Uint8Array(12));const k=await keyFromPassword(p,salt);data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},k,raw));rec.salt=b64(salt);rec.iv=b64(iv)}rec.blob=data.buffer;await put('files',rec);S.resources.unshift({...rec,blob:undefined});save();renderResources();toast(`${rec.type.toUpperCase()} պատրաստ է`)}
function renderResources(){const list=$('#file-list');if(!list)return;list.innerHTML=S.resources.slice(0,30).map(r=>`<div class="file-item"><span class="resource-icon">${r.protected?'🔐':'📄'}</span><div><strong>${esc(r.name)}</strong><small>${r.type.toUpperCase()} · ${esc(r.id)} · ${formatBytes(r.size||0)}</small></div><button class="ghost" data-fid="${esc(r.id)}">Կիսվել</button></div>`).join('');$$('[data-fid]').forEach(b=>b.onclick=()=>{copy(b.dataset.fid);msg('🔗 '+b.dataset.fid)})}
function resources(){const d=$('#resource-dialog');$('#new-resource').onclick=()=>d.showModal();$$('[data-action="create-resource"]').forEach(b=>b.onclick=()=>d.showModal());$('#pick-file').onclick=()=>$('#file-input').click();$('#file-input').onchange=e=>{[...e.target.files].forEach(f=>createResource(f,S.type==='pfid'));e.target.value=''};$$('.rtype').forEach(b=>b.onclick=()=>{S.type=b.dataset.type;$$('.rtype').forEach(x=>x.classList.toggle('active',x===b));$('#password-field')?.classList.toggle('hidden',!['pfid','psid'].includes(S.type))});$('#resource-form').onsubmit=e=>{e.preventDefault();d.close()}}
function startCall(video){if(!S.peer||S.peer.connectionState!=='connected')return toast('Նախ հաստատիր P2P կապը');callPC=new RTCPeerConnection({iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}]});callPC.onicecandidate=e=>{if(e.candidate)send({kind:'call-candidate',candidate:e.candidate})};callPC.ontrack=e=>{let v=$('#remote-media');if(!v){v=document.createElement('video');v.id='remote-media';v.autoplay=true;v.playsInline=true;v.controls=false;v.style.width='100%';$('#media-box').append(v)}v.srcObject=e.streams[0]};navigator.mediaDevices.getUserMedia({audio:true,video:video}).then(async stream=>{localStream=stream;const v=document.createElement('video');v.autoplay=true;v.muted=true;v.playsInline=true;v.id='local-media';v.srcObject=stream;v.style.width='100%';$('#media-box').append(v);stream.getTracks().forEach(t=>callPC.addTrack(t,stream));const offer=await callPC.createOffer();await callPC.setLocalDescription(offer);send({kind:'call-offer',description:callPC.localDescription,video})}).catch(()=>toast('Մեդիայի հասանելիությունը մերժվեց'))}
async function answerCall(m){if(callPC)return;callPC=new RTCPeerConnection({iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}]});callPC.onicecandidate=e=>{if(e.candidate)send({kind:'call-candidate',candidate:e.candidate})};callPC.ontrack=e=>{let v=$('#remote-media');if(!v){v=document.createElement('video');v.id='remote-media';v.autoplay=true;v.playsInline=true;v.style.width='100%';$('#media-box').append(v)}v.srcObject=e.streams[0]};await callPC.setRemoteDescription(m.description);localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:!!m.video});localStream.getTracks().forEach(t=>callPC.addTrack(t,localStream));const ans=await callPC.createAnswer();await callPC.setLocalDescription(ans);send({kind:'call-answer',description:callPC.localDescription})}
function hangup(){callPC?.close();callPC=null;localStream?.getTracks().forEach(t=>t.stop());localStream=null;$('#media-box')?.replaceChildren();toast('Զանգը ավարտվեց')}
function theme(){$$('.theme').forEach(b=>b.onclick=()=>{S.theme=b.dataset.theme;document.body.classList.toggle('light',S.theme==='light');save()})}
function clearData(){$('#clear-data').onclick=()=>{if(confirm('Մաքրել այս սարքի բոլոր AWEP2PAWE տվյալները՞')){localStorage.clear();indexedDB.deleteDatabase(DB);location.reload()}}}
async function init(){await loadIdentity();document.body.classList.toggle('light',S.theme==='light');$('#identity-id').textContent=S.id;$('#settings-id').textContent=S.id;save();nav();chats();messaging();resources();theme();clearData();injectNetworkUI();injectRooms();renderContacts();renderResources();const fi=$('#file-input');if(fi)fi.multiple=true;status('P2P կապը պատրաստ է')}
window.AWE={uid:()=>S.id,connect:acceptInvite,send,requestFID:id=>send({kind:'resource-request',id}),invite:makeOffer};
addEventListener('DOMContentLoaded',init);