/* AWEP2PAWE — 100% static browser runtime. WebRTC P2P, local storage, Web Crypto. */
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const DB_NAME='awep2pawe',DB_VERSION=1;
const state={identity:localStorage.getItem('awe_identity')||makeId('awe1'),theme:localStorage.getItem('awe_theme')||'dark',resources:JSON.parse(localStorage.getItem('awe_resources')||'[]'),selectedType:'fid',transferBuffer:[],transferMeta:null};
let rtc=null,channel=null;
function makeId(prefix){const b=crypto.getRandomValues(new Uint8Array(12));return prefix+':'+[...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
function save(){localStorage.setItem('awe_identity',state.identity);localStorage.setItem('awe_theme',state.theme);localStorage.setItem('awe_resources',JSON.stringify(state.resources))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function formatBytes(n){if(!n)return'';const u=['B','KB','MB','GB','TB'];let i=0,x=n;while(x>=1024&&i<u.length-1){x/=1024;i++}return x.toFixed(i?1:0)+' '+u[i]}
function toast(t){let e=$('#toast');if(!e){e=document.createElement('div');e.id='toast';e.className='toast';document.body.append(e)}e.textContent=t;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),2800)}
async function digest(bytes){const h=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function passwordKey(password,salt){const b=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:150000,hash:'SHA-256'},b,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('files'))d.createObjectStore('files',{keyPath:'id'});if(!d.objectStoreNames.contains('messages'))d.createObjectStore('messages',{keyPath:'id',autoIncrement:true})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbPut(store,value){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(store,'readwrite');t.objectStore(store).put(value);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function dbGet(store,key){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(store,'readonly'),r=t.objectStore(store).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function init(){document.body.classList.toggle('light',state.theme==='light');$('#identity-id').textContent=state.identity;$('#settings-id').textContent=state.identity;save();bindNavigation();bindChats();bindMessaging();bindResources();bindTheme();bindSearch();bindClear();renderSavedResources();addP2PPanel()}
function bindNavigation(){$$('.nav-item').forEach(b=>b.onclick=()=>{const v=b.dataset.view;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(x=>x.classList.remove('active-view'));$('#view-'+v)?.classList.add('active-view')})}
function bindChats(){$$('.chat-row').forEach(r=>r.onclick=()=>{$$('.chat-row').forEach(x=>x.classList.remove('selected'));r.classList.add('selected');$('#conversation-name').textContent=r.dataset.chat})}
function appendMessage(text,kind='outgoing',meta='հիմա ✓'){const m=document.createElement('div');m.className='message '+kind;m.innerHTML='<p></p><time>'+esc(meta)+'</time>';m.querySelector('p').textContent=text;$('#messages').append(m);$('#messages').scrollTop=$('#messages').scrollHeight}
function bindMessaging(){$('#message-form').onsubmit=async e=>{e.preventDefault();const i=$('#message-input'),text=i.value.trim();if(!text)return;appendMessage(text);i.value='';await dbPut('messages',{text,created:Date.now(),from:state.identity});if(channel?.readyState==='open')channel.send(JSON.stringify({kind:'chat',text}))}}
function bindResources(){const d=$('#resource-dialog');if(!d)return;$('#new-resource').onclick=()=>d.showModal();$$('[data-action="create-resource"]').forEach(x=>x.onclick=()=>d.showModal());$('#pick-file').onclick=()=>$('#file-input').click();$('#file-input').onchange=e=>{[...e.target.files].forEach(f=>createFileResource(f));e.target.value=''};$$('.rtype').forEach(b=>b.onclick=()=>selectType(b.dataset.type));$('#resource-form').onsubmit=async e=>{e.preventDefault();const name=$('#resource-name').value.trim()||'AWEP2PAWE resource',type=state.selectedType,pw=$('#resource-password')?.value||'';if(['pfid','psid'].includes(type)&&pw.length<8){toast('Private resource-ի գաղտնաբառը պետք է լինի առնվազն 8 նիշ');return}const item={id:makeId(type),type,name,created:Date.now(),protected:['pfid','psid'].includes(type),online:true,owner:state.identity};if(item.protected){const salt=crypto.getRandomValues(new Uint8Array(16));item.salt=btoa(String.fromCharCode(...salt));item.passwordCheck=await makePasswordCheck(pw,salt)}state.resources.unshift(item);save();d.close();$('#resource-name').value='';if($('#resource-password'))$('#resource-password').value='';renderResourceNotice(item);toast(type.toUpperCase()+' ստեղծվեց՝ '+item.id)}}
function selectType(type){state.selectedType=type;$$('.rtype').forEach(x=>x.classList.toggle('active',x.dataset.type===type));$('#password-field')?.classList.toggle('hidden',!['pfid','psid'].includes(type));if($('#resource-password'))$('#resource-password').required=['pfid','psid'].includes(type)}
async function makePasswordCheck(password,salt){const k=await passwordKey(password,salt);const raw=await crypto.subtle.exportKey('raw',k);return btoa(String.fromCharCode(...new Uint8Array(raw)))}
async function createFileResource(file){const bytes=await file.arrayBuffer(),hash=await digest(bytes),privateMode=state.selectedType==='pfid';let type=privateMode?'pfid':'fid',id=type+':'+hash.slice(0,32),record={id,type,name:file.name,size:file.size,mime:file.type||'application/octet-stream',created:Date.now(),online:true,owner:state.identity,hash,blob:bytes};if(privateMode){const pw=prompt('PFID գաղտնաբառը (առնվազն 8 նիշ)');if(!pw||pw.length<8){toast('Ֆայլը չի ստեղծվել');return}const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await passwordKey(pw,salt);record.blob=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,bytes);record.salt=btoa(String.fromCharCode(...salt));record.iv=btoa(String.fromCharCode(...iv));record.protected=true;record.passwordCheck=await makePasswordCheck(pw,salt)}await dbPut('files',record);state.resources.unshift({...record,blob:undefined});save();renderResourceNotice(record);toast(type.toUpperCase()+' պատրաստ է՝ '+id)}
function renderResourceNotice(item){const box=document.createElement('div');box.className='file-item';box.innerHTML='<span class="resource-icon">'+(item.protected?'🔐':'📄')+'</span><div><strong>'+esc(item.name)+'</strong><small>'+item.type.toUpperCase()+' · '+esc(item.id)+(item.size?' · '+formatBytes(item.size):'')+'</small></div><button class="ghost">Կիսվել</button>';$('#file-list')?.prepend(box);box.querySelector('button').onclick=()=>shareId(item)}
function renderSavedResources(){(state.resources||[]).slice(0,20).forEach(renderResourceNotice)}
function shareId(item){copyText(item.id);appendMessage('🔗 '+item.type.toUpperCase()+' · '+item.id);toast('ID-ը պատճենվեց')}
function bindTheme(){$$('.theme').forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;document.body.classList.toggle('light',state.theme==='light');$$('.theme').forEach(x=>x.classList.toggle('active',x===b));save()});$$('[data-copy="identity"]').forEach(x=>x.onclick=()=>copyText(state.identity))}
function bindSearch(){const i=$('#global-search');i.oninput=()=>{const q=i.value.toLowerCase();$$('.chat-row').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?'flex':'none')}}
function bindClear(){$('#clear-data').onclick=()=>{if(confirm('Այս սարքի տեղային տվյալները մաքրե՞լ։')){localStorage.clear();indexedDB.deleteDatabase(DB_NAME);location.reload()}}}
async function copyText(t){try{await navigator.clipboard.writeText(t);toast('Պատճենվեց')}catch{toast(t)}}
/* Real browser P2P using WebRTC DataChannel. Signaling is exchanged as text, so no signaling server is required. */
function addP2PPanel(){const host=$('#view-calls');if(!host||document.querySelector('#p2p-panel'))return;const p=document.createElement('section');p.id='p2p-panel';p.className='settings-panel';p.style.marginTop='14px';p.innerHTML='<div class="setting"><div><strong>Ուղիղ P2P կապ</strong><small>Ստեղծիր հրավեր կամ տեղադրիր ընկերոջ ուղարկած հրավերը։ Կապը սարք-սարք է։</small></div><button class="primary" id="p2p-create">Ստեղծել հրավեր</button></div><div class="setting"><div style="width:100%"><strong>Կապի կոդ</strong><textarea id="p2p-code" rows="6" style="width:100%;margin-top:8px;background:var(--surface2);color:var(--text);border:1px solid var(--border);border-radius:10px;padding:10px"></textarea><div style="display:flex;gap:8px;margin-top:8px;flex-wrap:wrap"><button class="ghost" id="p2p-copy">Պատճենել</button><button class="ghost" id="p2p-handle">Մշակել կոդը</button></div></div></div><div class="setting"><div><strong>Կարգավիճակ</strong><small id="p2p-status">Չկա ակտիվ կապ</small></div><span class="online-dot"></span></div>';host.append(p);$('#p2p-create').onclick=createOffer;$('#p2p-copy').onclick=()=>copyText($('#p2p-code').value);$('#p2p-handle').onclick=handleSignal}
function newRTC(){rtc=new RTCPeerConnection({iceServers:[]});rtc.onconnectionstatechange=()=>setP2PStatus('Կապ՝ '+rtc.connectionState);rtc.ondatachannel=e=>attachChannel(e.channel);return rtc}
function attachChannel(ch){channel=ch;channel.binaryType='arraybuffer';channel.onopen=()=>setP2PStatus('P2P կապը ակտիվ է');channel.onclose=()=>setP2PStatus('Կապը փակ է');channel.onmessage=handleP2PMessage}
function setP2PStatus(t){if($('#p2p-status'))$('#p2p-status').textContent=t}
async function waitIce(pc){if(pc.iceGatheringState==='complete')return;await new Promise(resolve=>{const f=()=>{if(pc.iceGatheringState==='complete'){pc.removeEventListener('icegatheringstatechange',f);resolve()}};pc.addEventListener('icegatheringstatechange',f);setTimeout(resolve,5000)})}
async function createOffer(){const pc=newRTC();attachChannel(pc.createDataChannel('awe'));const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);$('#p2p-code').value=btoa(JSON.stringify({type:'offer',description:pc.localDescription}));toast('Հրավերը պատրաստ է')}
async function handleSignal(){try{const x=JSON.parse(atob($('#p2p-code').value.trim()));if(x.type==='offer'){const pc=newRTC();await pc.setRemoteDescription(x.description);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await waitIce(pc);$('#p2p-code').value=btoa(JSON.stringify({type:'answer',description:pc.localDescription}));toast('Պատասխանը պատրաստ է․ ուղարկիր այն հրավիրողին')}else if(x.type==='answer'&&rtc){await rtc.setRemoteDescription(x.description);toast('Պատասխանը ընդունվեց')}}catch{toast('Կապի կոդը սխալ է')}}
async function handleP2PMessage(e){if(typeof e.data==='string'){let m;try{m=JSON.parse(e.data)}catch{return}if(m.kind==='resource-request')return serveResource(m);if(m.kind==='resource-meta'){state.transferMeta=m;state.transferBuffer=[];return}if(m.kind==='resource-end')return finishTransfer(m);if(m.kind==='protected'){toast('Այս ռեսուրսը private է․ անհրաժեշտ է գաղտնաբառ');return}if(m.kind==='chat')appendMessage(m.text,'incoming','P2P');return}state.transferBuffer.push(e.data)}
async function serveResource(m){const r=await dbGet('files',m.id);if(!r||!channel){channel?.send(JSON.stringify({kind:'error',message:'Resource unavailable'}));return}if(r.protected){channel.send(JSON.stringify({kind:'protected',id:r.id}));return}const bytes=new Uint8Array(r.blob);channel.send(JSON.stringify({kind:'resource-meta',id:r.id,name:r.name,mime:r.mime,size:bytes.byteLength,hash:r.hash}));for(let i=0;i<bytes.length;i+=65536){channel.send(bytes.slice(i,i+65536));await new Promise(requestAnimationFrame)}channel.send(JSON.stringify({kind:'resource-end',id:r.id,hash:r.hash}))}
async function finishTransfer(m){const total=state.transferBuffer.reduce((n,b)=>n+b.byteLength,0);const bytes=new Uint8Array(total);let o=0;for(const b of state.transferBuffer){bytes.set(new Uint8Array(b),o);o+=b.byteLength}const h=await digest(bytes);if(h!==m.hash){toast('Ֆայլի ստուգումը ձախողվեց');return}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([bytes],{type:state.transferMeta?.mime||'application/octet-stream'}));a.download=state.transferMeta?.name||'download';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);state.transferBuffer=[];state.transferMeta=null;toast('Ֆայլը ստացվեց և SHA-256-ով ստուգվեց')}
window.AWE={requestFID:id=>channel?.send(JSON.stringify({kind:'resource-request',id})),sendMessage:text=>channel?.send(JSON.stringify({kind:'chat',text}))};
window.addEventListener('DOMContentLoaded',init);