const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={resourceType:'fid',identity:localStorage.getItem('awe_identity')||makeId('awe1'),theme:localStorage.getItem('awe_theme')||'dark',resources:JSON.parse(localStorage.getItem('awe_resources')||'[]')};
function makeId(prefix){const bytes=crypto.getRandomValues(new Uint8Array(10));return prefix+':'+[...bytes].map(x=>x.toString(16).padStart(2,'0')).join('')}
function save(){localStorage.setItem('awe_identity',state.identity);localStorage.setItem('awe_theme',state.theme);localStorage.setItem('awe_resources',JSON.stringify(state.resources))}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2600)}
function init(){document.body.classList.toggle('light',state.theme==='light');$('#identity-id').textContent=state.identity;$('#settings-id').textContent=state.identity;save();bindNavigation();bindChats();bindMessaging();bindResources();bindTheme();bindSearch();bindClear()}
function bindNavigation(){$$('.nav-item').forEach(btn=>btn.onclick=()=>{const view=btn.dataset.view;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===btn));$$('.view').forEach(x=>x.classList.remove('active-view'));$('#view-'+view).classList.add('active-view')})}
function bindChats(){$$('.chat-row').forEach(row=>row.onclick=()=>{$$('.chat-row').forEach(x=>x.classList.remove('selected'));row.classList.add('selected');$('#conversation-name').textContent=row.dataset.chat})}
function bindMessaging(){$('#message-form').onsubmit=e=>{e.preventDefault();const input=$('#message-input'),text=input.value.trim();if(!text)return;const msg=document.createElement('div');msg.className='message outgoing';msg.innerHTML='<p></p><time>հիմա ✓</time>';msg.querySelector('p').textContent=text;$('#messages').append(msg);input.value='';$('#messages').scrollTop=$('#messages').scrollHeight}}
function bindResources(){const dialog=$('#resource-dialog');$('#new-resource').onclick=()=>dialog.showModal();$$('[data-action="create-resource"]').forEach(x=>x.onclick=()=>dialog.showModal());$('#pick-file').onclick=()=>$('#file-input').click();$('#file-input').onchange=e=>{[...e.target.files].forEach(file=>addFile(file));e.target.value=''};$$('.rtype').forEach(btn=>btn.onclick=()=>{state.resourceType=btn.dataset.type;$$('.rtype').forEach(x=>x.classList.toggle('active',x===btn));$('#password-field').classList.toggle('hidden',!['pfid','psid'].includes(state.resourceType));$('#resource-password').required=['pfid','psid'].includes(state.resourceType)});$('#resource-form').onsubmit=e=>{e.preventDefault();const name=$('#resource-name').value.trim();if(!name)return;const type=state.resourceType;const id=makeId(type);const item={id,type,name,created:Date.now(),protected:['pfid','psid'].includes(type)};state.resources.unshift(item);save();dialog.close();$('#resource-name').value='';$('#resource-password').value='';renderResourceNotice(item);toast(`${type.toUpperCase()} ստեղծվեց՝ ${id}`)} }
function renderResourceNotice(item){const box=document.createElement('div');box.className='file-item';box.innerHTML=`<span class="resource-icon">${item.protected?'🔐':'📦'}</span><div><strong>${escapeHtml(item.name)}</strong><small>${item.type.toUpperCase()} · ${item.id}</small></div><button class="ghost">Կիսվել</button>`;$('#file-list').prepend(box);box.querySelector('button').onclick=()=>copyText(item.id)}
function addFile(file){const type='fid',id=makeId(type);const item={id,type,name:file.name,size:file.size,created:Date.now()};state.resources.unshift(item);save();renderResourceNotice(item);toast(`FID ստեղծվեց՝ ${id}`)}
function bindTheme(){$$('.theme').forEach(btn=>btn.onclick=()=>{state.theme=btn.dataset.theme;document.body.classList.toggle('light',state.theme==='light');$$('.theme').forEach(x=>x.classList.toggle('active',x===btn));save()});$$('[data-copy="identity"]').forEach(x=>x.onclick=()=>copyText(state.identity))}
function bindSearch(){const input=$('#global-search');input.oninput=()=>{const q=input.value.toLowerCase();$$('.chat-row').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?'flex':'none')}}
function bindClear(){$('#clear-data').onclick=()=>{if(confirm('Մաքրել այս սարքի AWEP2PAWE տեղային տվյալները՞')){localStorage.removeItem('awe_resources');localStorage.removeItem('awe_identity');state.identity=makeId('awe1');state.resources=[];save();$('#identity-id').textContent=state.identity;$('#settings-id').textContent=state.identity;toast('Տեղային տվյալները մաքրվեցին')}}}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Պատճենվեց')}catch{toast(text)}}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
window.addEventListener('DOMContentLoaded',init);