(()=>{'use strict';
const loadPrivacy=()=>new Promise(resolve=>{const p=document.createElement('script');p.src='./privacy-file.js';p.onload=resolve;p.onerror=resolve;document.body.appendChild(p)});
const waitForQR=()=>new Promise((resolve,reject)=>{let n=0;const tick=()=>{if(typeof window.qrcode==='function'&&typeof window.QrScanner==='function')return resolve();if(++n>120)return reject(Error('QR libraries unavailable'));setTimeout(tick,100)};tick()});
const patchedRuntime=async()=>{
  const r=await fetch('./runtime.js',{cache:'no-store'});
  if(!r.ok)throw Error('runtime.js unavailable');
  let source=await r.text();
  source=source.replace("const q=qrcode(0,'M');q.addData(text,'Byte');q.make();box.innerHTML=q.createSvgTag(5,4);", "const q=qrcode(40,'L');q.addData(text,'Byte');q.make();box.innerHTML=q.createImgTag(6,4,'AWEP2PAWE QR');");
  source=source.replace("function downloadQR(){const svg=$('#qr svg');if(!svg)return toast('Generate a QR first');const u=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'})),a=document.createElement('a');a.href=u;a.download=`awe-chat-${S.chatId||'invite'}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}", "function downloadQR(){const img=$('#qr img');if(!img?.src)return toast('Generate a QR first');const a=document.createElement('a');a.href=img.src;a.download=`awe-chat-${S.chatId||'invite'}.png`;document.body.appendChild(a);a.click();a.remove()}");
  const replacement=`async function scan(){const d=$('#scanner'),v=$('#scan-video');if(!d||!v)return;if(!navigator.mediaDevices?.getUserMedia)return toast('Camera unavailable');try{d.showModal();$('#scanner-status').textContent='Starting camera…';if(typeof QrScanner==='function'){const scanner=new QrScanner(v,result=>{const raw=typeof result==='string'?result:result?.data;if(!raw)return;try{scanner.stop();scanner.destroy()}catch{}stopScanner();try{d.close()}catch{}decodeInput(raw).catch(()=>toast('Could not process QR'))},{preferredCamera:'environment',maxScansPerSecond:12,highlightScanRegion:true,highlightCodeOutline:true,onDecodeError:()=>{}});window.__aweQrScanner=scanner;await scanner.start();$('#scanner-status').textContent='Point the camera at the QR code…';return}v.srcObject=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});if(!('BarcodeDetector'in window))throw Error('QR scanner unavailable');const detector=new BarcodeDetector({formats:['qr_code']});const loop=async()=>{if(!d.open)return stopScanner();try{const z=await detector.detect(v),raw=z[0]?.rawValue;if(raw){stopScanner();d.close();await decodeInput(raw);return}}catch{}requestAnimationFrame(loop)};loop()}catch(e){try{window.__aweQrScanner?.stop();window.__aweQrScanner?.destroy()}catch{}stopScanner();try{d.close()}catch{}const m=String(e?.message||e);toast(/permission|denied/i.test(m)?'Camera permission denied':(/secure context|https/i.test(m)?'Camera requires HTTPS':'Camera could not start'));$('#scanner-status').textContent='Camera unavailable — choose a QR image instead.'}}
async function scanImage(file){if(!file)return;try{if(typeof QrScanner!=='function')throw Error('QR scanner unavailable');$('#scanner-status').textContent='Reading image…';const result=await QrScanner.scanImage(file,{returnDetailedScanResult:true,alsoTryWithoutScanRegion:true});const raw=typeof result==='string'?result:result?.data;if(!raw)throw Error('No QR code found');try{window.__aweQrScanner?.stop();window.__aweQrScanner?.destroy()}catch{}stopScanner();try{$('#scanner').close()}catch{}await decodeInput(raw)}catch(e){toast(/No QR/i.test(String(e))?'No QR code found in image':'Could not read QR image');$('#scanner-status').textContent='No readable QR found — try a clearer image.'}}
function send(`;
  const re=/async function scan\(\)\{[\s\S]*?function send\(/;
  if(re.test(source))source=source.replace(re,replacement);else throw Error('Runtime scanner section not found');
  const blob=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));
  const s=document.createElement('script');s.src=blob;s.onload=()=>setTimeout(()=>URL.revokeObjectURL(blob),1000);s.onerror=()=>{URL.revokeObjectURL(blob);throw Error('Patched runtime failed')};document.body.appendChild(s);
};
const start=async()=>{if(window.__aweRuntimeStarted)return;window.__aweRuntimeStarted=true;try{await loadPrivacy();await waitForQR();await patchedRuntime()}catch(e){const status=document.querySelector('#qr-status');if(status)status.textContent='Startup error — refresh the page';const toast=document.querySelector('#toast');if(toast){toast.textContent='AWEP2PAWE could not start: '+(e?.message||e);toast.classList.add('show')}}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
