(()=>{'use strict';
/* CFID is a signed-free, content-addressed reference. It never uploads data. */
const KEY='AWEP2PAWE_STATE_V11';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
const uid=()=>window.AWEStateStore?.getIdentity().then(x=>x.uid).catch(()=>null);
const clean=v=>String(v||'').trim();
const validId=v=>/^CFID-[A-F0-9]{24}$/.test(v)||/^(FID|PFID|SID|PSID)-[A-F0-9]{40}$/.test(v);
function encodeRef(r){return `cfid://${r.id}`}
function parseRef(input){const v=clean(input);if(v.startsWith('cfid://'))return v.slice(7).split(/[?#]/,1)[0].toUpperCase();return v.toUpperCase()}
async function create(target){if(!target||!validId(target.id))throw Error('Invalid resource reference');const owner=await uid();const canonical=JSON.stringify({target:target.id,kind:target.type,hash:target.sha256||target.hash||target.manifestHash||null,owner});const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical));const suffix=[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,24).toUpperCase();const ref={id:`CFID-${suffix}`,type:'cfid',target:target.id,owner,proofHash:[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join(''),created:Date.now(),onlineOnly:true,scheme:'cfid://'};const s=read();s.resources=Array.isArray(s.resources)?s.resources:[];s.resources=s.resources.filter(x=>x.id!==ref.id);s.resources.unshift(ref);write(s);return ref}
function find(id){const s=read();return s.resources?.find(x=>x.id===id)||null}
async function resolve(input){const id=parseRef(input);if(!validId(id))throw Error('Invalid CFID/resource reference');const s=read();let ref=s.resources?.find(x=>x.id===id);if(id.startsWith('CFID-')){if(!ref)throw Error('CFID is not present on this device');const target=s.resources?.find(x=>x.id===ref.target);if(!target)throw Error('Referenced resource is not present on this device');return {reference:ref,target,local:true}}const target=s.resources?.find(x=>x.id===id);if(target)return {reference:null,target,local:true};throw Error('Resource is not available locally; its owner must be online for direct P2P serving')}
async function share(target){const r=await create(target);try{await navigator.clipboard.writeText(encodeRef(r))}catch{};return r}
window.AWECFID={create,find,resolve,share,encode:encodeRef,parse:parseRef,isValid:validId};
window.addEventListener('load',()=>{const button=document.querySelector('#make-cfid');if(button&&!button.dataset.cfidBound){button.dataset.cfidBound='1';button.onclick=async()=>{try{const s=read(),targets=(s.resources||[]).filter(x=>['fid','pfid','sid','psid'].includes(x.type));if(!targets.length)throw Error('Create a resource first');const labels=targets.map((x,i)=>`${i+1}. ${x.id} — ${x.name||x.type}`).join('\n');const n=Number(prompt(`Select resource to reference:\n${labels}`, '1'));const target=targets[n-1];if(!target)throw Error('Invalid resource selection');const r=await share(target);const d=document.querySelector('#id-dialog');if(d){document.querySelector('#id-title').textContent='CFID';document.querySelector('#id-value').value=r.id;document.querySelector('#id-details').textContent=JSON.stringify(r,null,2);d.showModal()} }catch(e){const t=document.querySelector('#toast');if(t){t.textContent=e.message;t.classList.add('show')}}}}});
})();
