(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORE='awep2pawe:v6', FILE_DB='awep2pawe-files';
const uidAlphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const now=()=>Date.now();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const short=s=>s&&s.length>22?s.slice(0,10)+'…'+s.slice(-8):s;
const toast=m=>{const e=$('#toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2400)};
const copy=async s=>{try{await navigator.clipboard.writeText(s);toast('Copied')}catch{prompt('Copy',s)}};
const load=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}};
let db=load();
db.uid ||= 'AWE-'+crypto.randomUUID().replaceAll('-','').slice(0,20).toUpperCase();
db.chats ||= []; db.contacts ||= []; db.channels ||= []; db.resources ||= []; db.blocks ||= []; db.calls ||= []; db.settings ||= {lang:'en',theme:'light'};
const save=()=>localStorage.setItem(STORE,JSON.stringify(db));
$('#identity-id').textContent=db.uid; $('#settings-id').textContent=db.uid;
$('#copy-uid')?.addEventListener('click',()=>copy(db.uid)); $('#copy-uid-2')?.addEventListener('click',()=>copy(db.uid));

/* ---------- language ---------- */
const I18N={en:{chats:'Chats',people:'People',channels:'Channels',resources:'Resources',calls:'Calls',settings:'Settings',search:'Search AWE UID, FID, PFID, SID, PSID or CFID…',newchat:'New chat',empty:'No open chats yet',write:'Write a message…'},hy:{chats:'Չատեր',people:'Մարդիկ',channels:'Ալիքներ',resources:'Ռեսուրսներ',calls:'Զանգեր',settings:'Կարգավորումներ',search:'Որոնել AWE UID, FID, PFID, SID, PSID կամ CFID…',newchat:'Նոր չատ',empty:'Բաց չատեր չկան',write:'Գրել հաղորդագրություն…'},ru:{chats:'Чаты',people:'Люди',channels:'Каналы',resources:'Ресурсы',calls:'Звонки',settings:'Настройки',search:'Поиск AWE UID, FID, PFID, SID, PSID или CFID…',newchat:'Новый чат',empty:'Нет открытых чатов',write:'Сообщение…'},es:{chats:'Chats',people:'Personas',channels:'Canales',resources:'Recursos',calls:'Llamadas',settings:'Ajustes',search:'Buscar AWE UID, FID, PFID, SID, PSID o CFID…',newchat:'Nuevo chat',empty:'No hay chats abiertos',write:'Escribe un mensaje…'},fr:{chats:'Discussions',people:'Personnes',channels:'Canaux',resources:'Ressources',calls:'Appels',settings:'Réglages',search:'Rechercher AWE UID, FID, PFID, SID, PSID ou CFID…',newchat:'Nouvelle discussion',empty:'Aucune discussion',write:'Écrire un message…'},de:{chats:'Chats',people:'Personen',channels:'Kanäle',resources:'Ressourcen',calls:'Anrufe',settings:'Einstellungen',search:'AWE UID, FID, PFID, SID, PSID oder CFID suchen…',newchat:'Neuer Chat',empty:'Keine offenen Chats',write:'Nachricht schreiben…'},pt:{chats:'Chats',people:'Pessoas',channels:'Canais',resources:'Recursos',calls:'Chamadas',settings:'Definições',search:'Pesquisar AWE UID, FID, PFID, SID, PSID ou CFID…',newchat:'Novo chat',empty:'Sem chats abertos',write:'Escreva uma mensagem…'},ar:{chats:'المحادثات',people:'الأشخاص',channels:'القنوات',resources:'الموارد',calls:'المكالمات',settings:'الإعدادات',search:'ابحث عن AWE UID أو FID أو PFID أو SID أو PSID أو CFID…',newchat:'محادثة جديدة',empty:'لا توجد محادثات',write:'اكتب رسالة…'},hi:{chats:'चैट',people:'लोग',channels:'चैनल',resources:'संसाधन',calls:'कॉल',settings:'सेटिंग्स',search:'AWE UID, FID, PFID, SID, PSID या CFID खोजें…',newchat:'नई चैट',empty:'कोई चैट नहीं',write:'संदेश लिखें…'},zh:{chats:'聊天',people:'联系人',channels:'频道',resources:'资源',calls:'通话',settings:'设置',search:'搜索 AWE UID、FID、PFID、SID、PSID 或 CFID…',newchat:'新聊天',empty:'暂无聊天',write:'输入消息…'},tr:{chats:'Sohbetler',people:'Kişiler',channels:'Kanallar',resources:'Kaynaklar',calls:'Aramalar',settings:'Ayarlar',search:'AWE UID, FID, PFID, SID, PSID veya CFID ara…',newchat:'Yeni sohbet',empty:'Açık sohbet yok',write:'Mesaj yaz…'},fa:{chats:'گفتگوها',people:'افراد',channels:'کانال‌ها',resources:'منابع',calls:'تماس‌ها',settings:'تنظیمات',search:'جستجوی AWE UID، FID، PFID، SID، PSID یا CFID…',newchat:'گفتگوی جدید',empty:'گفتگویی وجود ندارد',write:'پیام بنویسید…'}};
function applyLang(){const l=I18N[db.settings.lang]||I18N.en;document.documentElement.lang=db.settings.lang;const nav=[['chats',l.chats],['contacts',l.people],['channels',l.channels],['resources',l.resources],['calls',l.calls],['settings',l.settings]];nav.forEach(([v,t])=>$$(`[data-view="${v}"] span`).forEach(e=>e.textContent=t));$('#global-search').placeholder=l.search;$('#new-chat').textContent='＋ '+l.newchat;$('#message-input').placeholder=l.write;}
applyLang();

/* ---------- navigation ---------- */
let activeView='chats', activeChat=null, peer=null, pc=null, dc=null, localStream=null, incomingFile=null;
function showView(v){activeView=v;$$('.view').forEach(x=>x.classList.toggle('active-view',x.id==='view-'+v));$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='chats')renderChats();if(v==='contacts')renderPeople();if(v==='channels')renderChannels();if(v==='resources')renderResources();if(v==='calls')renderCalls();}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
$('#theme-light')?.addEventListener('click',()=>{db.settings.theme='light';document.body.className='light';save()});
$('#theme-dark')?.addEventListener('click',()=>{db.settings.theme='dark';document.body.className='dark';save()});
if(db.settings.theme==='dark')document.body.className='dark'; else document.body.className='light';

/* ---------- chat model ---------- */
const chatById=id=>db.chats.find(c=>c.id===id);
function createChat(uid,name=''){uid=uid.trim().toUpperCase();if(uid===db.uid.toUpperCase())return toast('That is your own UID');if(!/^AWE-[A-Z0-9]+$/.test(uid))return toast('Invalid AWE UID');if(db.blocks.includes(uid))return toast('This UID is blocked');let c=db.chats.find(x=>x.peer===uid&&x.type==='direct');if(!c){c={id:crypto.randomUUID(),peer:uid,name:name||uid,type:'direct',messages:[],unread:0,last:'New conversation',updated:now()};db.chats.unshift(c);if(!db.contacts.some(x=>x.uid===uid))db.contacts.unshift({uid,name:name||uid});save()}openChat(c.id);return c}
function openChat(id){const c=chatById(id);if(!c||db.blocks.includes(c.peer))return;activeChat=id;c.updated=now();c.unread=0;save();$('#conversation-empty').classList.add('hidden');$('#conversation-content').classList.remove('hidden');$('#conversation-name').textContent=c.name||short(c.peer);$('#conversation-avatar').textContent=(c.name||c.peer).slice(0,1).toUpperCase();$('#p2p-status').textContent=peer?.uid===c.peer?'connected':'offline';renderChats();renderMessages()}
function renderChats(){const box=$('#chat-items');if(!box)return;const filter=document.querySelector('.filter.active')?.dataset.filter||'all';let arr=db.chats.filter(c=>filter==='all'||filter==='groups'&&(c.type==='group'||c.type==='channel')||filter==='unread'&&c.unread);arr.sort((a,b)=>(b.updated||0)-(a.updated||0));box.innerHTML=arr.map(c=>`<button class="chat-row ${c.id===activeChat?'selected':''}" data-chat="${c.id}"><span class="avatar ${c.type==='channel'?'orange':'purple'}">${esc((c.name||c.peer||'A').slice(0,1).toUpperCase())}</span><span class="chat-meta"><strong>${esc(c.name||short(c.peer))}</strong><small>${esc(c.last||'')}</small></span>${c.unread?`<b class="unread-dot">${Math.min(c.unread,99)}</b>`:''}</button>`).join('');$('#chat-empty').style.display=arr.length?'none':'flex';$$('[data-chat]').forEach(b=>b.onclick=()=>openChat(b.dataset.chat))}
function renderMessages(){const c=chatById(activeChat),box=$('#messages');if(!box)return;box.innerHTML=c?(c.messages||[]).map(m=>`<div class="bubble-row ${m.mine?'mine':''}"><div class="bubble ${m.mine?'mine':''}">${m.file?`📎 <strong>${esc(m.file.name)}</strong><small>${esc(m.file.id)} · ${Math.round(m.file.size/1024)} KB</small>`:esc(m.text||'')}<time>${new Date(m.ts).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time></div></div>`).join(''):'';box.scrollTop=box.scrollHeight}
$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderChats()}));
function addMessage(c,m){c.messages??=[];c.messages.push(m);c.last=m.file?'📎 '+m.file.name:(m.text||'');c.updated=now();save();if(activeChat===c.id)renderMessages();renderChats()}
function sendText(text){const c=chatById(activeChat);if(!c)return;if(db.blocks.includes(c.peer))return toast('Blocked');const m={t:'msg',id:crypto.randomUUID(),text,ts:now(),from:db.uid};addMessage(c,{...m,mine:true});sendPacket(m)}
$('#message-form')?.addEventListener('submit',e=>{e.preventDefault();const i=$('#message-input'),t=i.value.trim();if(t)sendText(t);i.value=''});
$('#new-chat')?.addEventListener('click',()=>{const uid=prompt('Enter AWE UID');if(uid)createChat(uid)});$('#new-chat-2')?.addEventListener('click',()=>{const uid=prompt('Enter AWE UID');if(uid)createChat(uid)});

/* ---------- identity-aware search ---------- */
function handleSearch(q){q=q.trim();if(!q)return;if(/^AWE-[A-Z0-9]+$/i.test(q))return createChat(q);const r=db.resources.find(x=>x.id.toLowerCase()===q.toLowerCase());if(r){showView('resources');return showId(r)}const ch=db.chats.find(x=>x.id===q||x.peer.toLowerCase()===q.toLowerCase());if(ch)return openChat(ch.id);const channel=db.channels.find(x=>x.id.toLowerCase()===q.toLowerCase());if(channel){showView('channels');toast('Channel found');return}toast('ID is not known on this device. A direct peer connection is required to exchange it.');}
$('#search-go')?.addEventListener('click',()=>handleSearch($('#global-search').value));$('#global-search')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();handleSearch(e.target.value)}});

/* ---------- block/delete/menu ---------- */
function blockPeer(uid){uid=uid.toUpperCase();if(!db.blocks.includes(uid))db.blocks.push(uid);db.chats=db.chats.filter(c=>c.peer!==uid);db.contacts=db.contacts.filter(c=>c.uid!==uid);if(activeChat&&chatById(activeChat)?.peer===uid){activeChat=null;$('#conversation-content').classList.add('hidden');$('#conversation-empty').classList.remove('hidden')}save();renderChats();renderPeople();toast('Blocked locally')}
$('#chat-menu')?.addEventListener('click',()=>$('#chat-menu-dialog').showModal());$('#chat-menu-close')?.addEventListener('click',()=>$('#chat-menu-dialog').close());
$('#delete-chat')?.addEventListener('click',()=>{if(!activeChat)return;db.chats=db.chats.filter(c=>c.id!==activeChat);activeChat=null;$('#chat-menu-dialog').close();$('#conversation-content').classList.add('hidden');$('#conversation-empty').classList.remove('hidden');save();renderChats()});
$('#block-chat')?.addEventListener('click',()=>{const c=chatById(activeChat);if(c)blockPeer(c.peer);$('#chat-menu-dialog').close()});
$('#rename-chat')?.addEventListener('click',()=>{const c=chatById(activeChat);if(c){const n=prompt('Chat name',c.name);if(n?.trim()){c.name=n.trim();save();openChat(c.id)}}$('#chat-menu-dialog').close()});
$('#back-chats')?.addEventListener('click',()=>{$('#conversation-content').classList.add('hidden');$('#conversation-empty').classList.remove('hidden')});
$('#show-blocks')?.addEventListener('click',()=>alert(db.blocks.length?db.blocks.join('\n'):'No blocked IDs'));
$('#clear-data')?.addEventListener('click',()=>{if(confirm('Delete all local AWEP2PAWE data?')){localStorage.removeItem(STORE);location.reload()}});

/* ---------- WebRTC: direct, no application backend ---------- */
const rtcConfig={iceServers:[]};
function makePeer(isInitiator){if(pc)pc.close();pc=new RTCPeerConnection(rtcConfig);pc.onconnectionstatechange=()=>{const s=pc.connectionState;$('#p2p-status').textContent=s;if(s==='failed')toast('Peer connection failed');};pc.ondatachannel=e=>attachChannel(e.channel);if(isInitiator)attachChannel(pc.createDataChannel('awe-data',{ordered:true}));pc.onicecandidate=()=>{if(pc.iceGatheringState==='complete')exportSignal()};return pc}
function attachChannel(c){dc=c;dc.binaryType='arraybuffer';dc.onopen=()=>{$('#p2p-status').textContent='connected';sendPacket({t:'hello',uid:db.uid});toast('P2P connected')};dc.onclose=()=>$('#p2p-status').textContent='disconnected';dc.onmessage=e=>receivePacket(e.data)}
function exportSignal(){const d=pc?.localDescription;if(!d)return;const payload=btoa(JSON.stringify({v:1,type:d.type,sdp:d.sdp,uid:db.uid}));$('#signal-code').value=payload;$('#signal-dialog').showModal()}
async function startOffer(){if(!activeChat)return toast('Open a chat first');makePeer(true);await pc.createOffer().then(o=>pc.setLocalDescription(o));await waitIce();exportSignal()}
async function waitIce(){if(pc.iceGatheringState==='complete')return;await new Promise(resolve=>{const t=setTimeout(resolve,5000);pc.addEventListener('icegatheringstatechange',()=>{if(pc.iceGatheringState==='complete'){clearTimeout(t);resolve()}})})}
async function acceptSignal(code){try{const o=JSON.parse(atob(code.trim()));if(!o.sdp||!o.type)throw 0;if(o.type==='offer'){makePeer(false);await pc.setRemoteDescription(o);const a=await pc.createAnswer();await pc.setLocalDescription(a);await waitIce();exportSignal()}else{if(!pc)makePeer(true);await pc.setRemoteDescription(o);$('#signal-dialog').close();toast('Answer applied')}}catch(e){toast('Invalid connection code')}}
function sendPacket(obj){if(dc?.readyState==='open')dc.send(JSON.stringify(obj))}
$('#connect')?.addEventListener('click',startOffer);$('#signal-close')?.addEventListener('click',()=>$('#signal-dialog').close());$('#copy-signal')?.addEventListener('click',()=>copy($('#signal-code').value));$('#paste-signal')?.addEventListener('click',()=>{const c=prompt('Paste peer connection code');if(c)acceptSignal(c)});

/* ---------- file store + FID/PFID/CFID ---------- */
function openFileDB(){return new Promise((res,rej)=>{const r=indexedDB.open(FILE_DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('files',{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putFile(id,file){const d=await openFileDB();return new Promise((res,rej)=>{const t=d.transaction('files','readwrite');t.objectStore('files').put({id,name:file.name,size:file.size,type:file.type,blob:file,created:now()});t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function getFile(id){const d=await openFileDB();return new Promise((res,rej)=>{const t=d.transaction('files');const r=t.objectStore('files').get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function shaFile(file){const h=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase()}
async function createFileResource(kind,file,password=''){const hash=await shaFile(file), id=kind.toLowerCase()+'_'+hash.slice(0,32);await putFile(id,file);const r={id,kind,name:file.name,size:file.size,type:file.type,hash,created:now(),private:kind==='PFID'||kind==='PSID'};if(password){const salt=crypto.getRandomValues(new Uint8Array(16));r.salt=btoa(String.fromCharCode(...salt));r.passHash=await derivePassword(password,salt)}db.resources.unshift(r);save();renderResources();showId(r);return r}
async function derivePassword(p,salt){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);const b=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:150000,hash:'SHA-256'},k,256);return btoa(String.fromCharCode(...new Uint8Array(b)))}
async function chooseResource(kind){const inp=$('#file-input');inp.dataset.kind=kind;inp.click()}
$('#make-fid')?.addEventListener('click',()=>chooseResource('FID'));$('#make-pfid')?.addEventListener('click',async()=>{const p=prompt('Private file password');if(p)chooseResource('PFID')});
$('#file-input')?.addEventListener('change',async e=>{const f=e.target.files?.[0],kind=e.target.dataset.kind;e.target.value='';if(!f||!kind)return;let p='';if(kind==='PFID')p=prompt('Private file password')||'';if(kind==='PFID'&&!p)return;await createFileResource(kind,f,p)});
$('#make-cfid')?.addEventListener('click',async()=>{const id=prompt('Paste an existing FID/PFID/SID/PSID');if(!id)return;const r={id:'cfid_'+await hashText(id),kind:'CFID',target:id,created:now()};db.resources.unshift(r);save();renderResources();showId(r)});
async function hashText(s){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,40).toUpperCase()}
function renderResources(){const box=$('#resource-list');if(!box)return;box.innerHTML=db.resources.map(r=>`<button class="resource-line" data-r="${esc(r.id)}"><span>${r.private?'🔐':r.kind==='CFID'?'⚡':r.kind==='SID'||r.kind==='PSID'?'🌐':'📄'}</span><span><strong>${esc(r.name||r.target||r.kind)}</strong><small>${esc(r.id)}</small></span><i>›</i></button>`).join('')||'<div class="empty-card">No resources yet.</div>';$$('.resource-line').forEach(b=>b.onclick=()=>showId(db.resources.find(r=>r.id===b.dataset.r)))}
function showId(r){if(!r)return;$('#id-title').textContent=r.kind+' resource';$('#id-value').value=r.id;$('#id-details').textContent=JSON.stringify(r,null,2);$('#id-dialog').showModal()}
$('#id-close')?.addEventListener('click',()=>$('#id-dialog').close());$('#id-copy')?.addEventListener('click',()=>copy($('#id-value').value));

/* ---------- folders / SID ---------- */
async function createFolderResource(kind,files){if(!files?.length)return;const manifest=[];for(const f of files){manifest.push({path:f.webkitRelativePath||f.name,size:f.size,type:f.type});}const id=kind.toLowerCase()+'_'+await hashText(JSON.stringify(manifest));const r={id,kind,name:manifest[0].path.split('/')[0],files:manifest,count:files.length,created:now(),private:kind==='PSID'};db.resources.unshift(r);save();renderResources();showId(r)}
$('#make-sid')?.addEventListener('click',()=>{$('#folder-input').dataset.kind='SID';$('#folder-input').click()});$('#make-psid')?.addEventListener('click',()=>{$('#folder-input').dataset.kind='PSID';$('#folder-input').click()});$('#folder-input')?.addEventListener('change',async e=>{const k=e.target.dataset.kind;e.target.value='';if(!k)return;let p='';if(k==='PSID'){p=prompt('Private SID password')||'';if(!p)return}await createFolderResource(k,e.target.files) });

/* ---------- channels ---------- */
$('#create-channel')?.addEventListener('click',()=>{const name=prompt('Channel name');if(!name)return;const c={id:'CH-'+crypto.randomUUID().replaceAll('-','').slice(0,18).toUpperCase(),name,type:'channel',members:[db.uid],messages:[],created:now()};db.channels.unshift(c);db.chats.unshift({id:'chat-'+c.id,peer:c.id,name:c.name,type:'channel',messages:[],last:'Channel created',updated:now()});save();renderChannels();renderChats();toast('Channel created')});
function renderChannels(){const box=$('#channel-list');if(!box)return;box.innerHTML=db.channels.map(c=>`<div class="info-card"><span class="avatar orange">📢</span><div><strong>${esc(c.name)}</strong><small>${esc(c.id)} · ${c.members.length} member(s)</small></div><button class="ghost" data-invite="${esc(c.id)}">Invite</button></div>`).join('')||'<div class="empty-card">No channels yet.</div>';$$('[data-invite]').forEach(b=>b.onclick=()=>{const uid=prompt('Invite AWE UID');if(!uid)return;const c=db.channels.find(x=>x.id===b.dataset.invite);if(c&&!c.members.includes(uid.toUpperCase()))c.members.push(uid.toUpperCase());save();toast('Invite prepared locally')})}
function renderPeople(){const box=$('#people-list');if(!box)return;box.innerHTML=db.contacts.map(p=>`<div class="info-card"><span class="avatar purple">${esc((p.name||'A').slice(0,1).toUpperCase())}</span><div><strong>${esc(p.name||p.uid)}</strong><small>${esc(p.uid)}</small></div><button class="ghost" data-person="${esc(p.uid)}">Chat</button><button class="ghost danger-lite" data-block="${esc(p.uid)}">Block</button></div>`).join('')||'<div class="empty-card">No contacts yet.</div>';$$('[data-person]').forEach(b=>b.onclick=()=>createChat(b.dataset.person));$$('[data-block]').forEach(b=>b.onclick=()=>blockPeer(b.dataset.block))}

/* ---------- binary file transfer ---------- */
let rx={};
async function sendFileP2P(file,id){if(!dc||dc.readyState!=='open')return toast('Connect to the peer first');const chunk=64*1024,total=Math.ceil(file.size/chunk);sendPacket({t:'file-start',id,name:file.name,size:file.size,type:file.type,total});for(let i=0;i<total;i++){const data=await file.slice(i*chunk,(i+1)*chunk).arrayBuffer();while(dc.bufferedAmount>2*1024*1024)await new Promise(r=>setTimeout(r,15));dc.send(data)}sendPacket({t:'file-end',id});toast('File sent')}
async function receivePacket(raw){if(typeof raw==='string'){try{const m=JSON.parse(raw);if(m.t==='hello'){peer={uid:m.uid};if(m.uid&&!db.chats.some(c=>c.peer===m.uid))createChat(m.uid);return}if(m.t==='msg'){const c=db.chats.find(x=>x.peer===m.from)||db.chats.find(x=>x.id===activeChat);if(c){addMessage(c,{...m,mine:false});c.unread=activeChat===c.id?0:(c.unread||0)+1;save()}return}if(m.t==='file-start'){rx[m.id]={meta:m,parts:[]};toast('Receiving '+m.name);return}if(m.t==='file-end'){const r=rx[m.id];if(!r)return;const blob=new Blob(r.parts,{type:r.meta.type||'application/octet-stream'});const f=new File([blob],r.meta.name,{type:r.meta.type});await putFile(r.meta.id,f);const c=activeChat&&chatById(activeChat);if(c)addMessage(c,{mine:false,ts:now(),file:{id:r.meta.id,name:r.meta.name,size:r.meta.size}});delete rx[m.id];return}}catch{}}else{const keys=Object.keys(rx);if(keys.length)rx[keys[keys.length-1]].parts.push(raw)}}
$('#pick-file')?.addEventListener('click',()=>$('#file-input').click());
$('#file-input')?.addEventListener('change',async e=>{if(e.target.dataset.kind)return;const f=e.target.files?.[0];e.target.value='';if(!f||!activeChat)return;const id='fid_'+await shaFile(f).then(x=>x.slice(0,32));await putFile(id,f);addMessage(chatById(activeChat),{mine:true,ts:now(),file:{id,name:f.name,size:f.size}});sendFileP2P(f,id)});

/* ---------- media calls ---------- */
async function openCall(kind){if(!activeChat)return toast('Open a chat first');$('#call-overlay').classList.remove('hidden');$('#call-title').textContent=kind==='video'?'Video call':kind==='screen'?'Screen sharing':'Voice call';$('#call-state').textContent=dc?.readyState==='open'?'P2P media ready':'Waiting for peer';try{localStream=kind==='screen'?await navigator.mediaDevices.getDisplayMedia({video:true,audio:true}):await navigator.mediaDevices.getUserMedia({audio:true,video:kind==='video'});if(pc)localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));$('#local-video').srcObject=localStream;db.calls.unshift({peer:chatById(activeChat)?.peer,kind,ts:now()});save();renderCalls()}catch{toast('Media permission denied')}}
$('#voice')?.addEventListener('click',()=>openCall('voice'));$('#video')?.addEventListener('click',()=>openCall('video'));$('#screen')?.addEventListener('click',()=>openCall('screen'));$('#call-screen')?.addEventListener('click',()=>openCall('screen'));$('#call-mute')?.addEventListener('click',()=>localStream?.getAudioTracks().forEach(t=>t.enabled=!t.enabled));$('#call-camera')?.addEventListener('click',()=>localStream?.getVideoTracks().forEach(t=>t.enabled=!t.enabled));function closeCall(){localStream?.getTracks().forEach(t=>t.stop());localStream=null;$('#local-video').srcObject=null;$('#call-overlay').classList.add('hidden')}$('#call-close')?.addEventListener('click',closeCall);$('#call-hangup')?.addEventListener('click',closeCall);
function renderCalls(){const b=$('#call-history');if(!b)return;b.innerHTML=db.calls.map(c=>`<div class="info-card"><span class="avatar purple">☎</span><div><strong>${esc(c.kind)}</strong><small>${esc(c.peer||'Unknown')} · ${new Date(c.ts).toLocaleString()}</small></div></div>`).join('')||'<div class="empty-card">No calls yet.</div>'}

/* ---------- settings language selector ---------- */
const settingsPanel=$('.settings-panel');if(settingsPanel&&!$('#language-select')){const row=document.createElement('div');row.className='setting';row.innerHTML='<div><strong>Language</strong><small>English is the default. More than 10 languages are available.</small></div><select id="language-select"><option value="en">English</option><option value="hy">Հայերեն</option><option value="ru">Русский</option><option value="es">Español</option><option value="fr">Français</option><option value="de">Deutsch</option><option value="pt">Português</option><option value="ar">العربية</option><option value="hi">हिन्दी</option><option value="zh">简体中文</option><option value="tr">Türkçe</option><option value="fa">فارسی</option></select>';settingsPanel.prepend(row);$('#language-select').value=db.settings.lang;$('#language-select').onchange=e=>{db.settings.lang=e.target.value;save();applyLang()}}

/* ---------- accessibility / safe defaults ---------- */
window.addEventListener('error',e=>console.error('AWEP2PAWE',e.error||e.message));
window.addEventListener('unhandledrejection',e=>console.error('AWEP2PAWE',e.reason));
renderChats();renderPeople();renderChannels();renderResources();renderCalls();
})();