(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='awep2pawe:v4';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return {}}};
let db=load();
db.uid=db.uid||('AWE-'+crypto.randomUUID().replaceAll('-','').toUpperCase());
db.chats=db.chats||[]; db.contacts=db.contacts||[]; db.channels=db.channels||[]; db.resources=db.resources||[]; db.blocks=db.blocks||[]; db.calls=db.calls||[];
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),2600)};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const short=s=>s?.length>20?s.slice(0,10)+'…'+s.slice(-7):s;
$('#identity-id').textContent=db.uid; $('#settings-id').textContent=db.uid;
const copy=async t=>{try{await navigator.clipboard.writeText(t);toast('Copied')}catch{prompt('Copy',t)}};
$('#copy-uid').onclick=()=>copy(db.uid);$('#copy-uid-2').onclick=()=>copy(db.uid);

function showView(name){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id==='view-'+name));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name)); if(name==='chats')renderChats();if(name==='contacts')renderPeople();if(name==='channels')renderChannels();if(name==='resources')renderResources();if(name==='calls')renderCalls();}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$('#theme-light').onclick=()=>{document.body.className='light';localStorage.setItem('awe-theme','light')};$('#theme-dark').onclick=()=>{document.body.className='dark';localStorage.setItem('awe-theme','dark')};
if(localStorage.getItem('awe-theme')==='dark')document.body.className='dark';

let activeChat=null, pc=null, dc=null, localStream=null, remoteStream=null, pendingIce=[];
const chatById=id=>db.chats.find(c=>c.id===id);
function openChat(id){const c=chatById(id);if(!c||db.blocks.includes(c.peer))return;activeChat=id;c.lastOpened=Date.now();save();$('#conversation-empty').classList.add('hidden');$('#conversation-content').classList.remove('hidden');$('#conversation-name').textContent=c.name||short(c.peer);$('#conversation-avatar').textContent=(c.name||c.peer).slice(0,1).toUpperCase();renderMessages();renderChats();}
function renderChats(){const box=$('#chat-items');box.innerHTML='';const filter=document.querySelector('.filter.active')?.dataset.filter||'all';const arr=db.chats.filter(c=>filter==='all'||(filter==='groups'&&c.type==='group')||(filter==='unread'&&c.unread));arr.sort((a,b)=>(b.lastOpened||0)-(a.lastOpened||0));$('#chat-empty').style.display=arr.length?'none':'flex';arr.forEach(c=>{const b=document.createElement('button');b.className='chat-row '+(c.id===activeChat?'selected':'');b.innerHTML=`<span class="avatar ${c.type==='channel'?'orange':'purple'}">${esc((c.name||c.peer).slice(0,1).toUpperCase())}</span><span class="chat-row-main"><strong>${esc(c.name||short(c.peer))}</strong><small>${esc(c.last||c.peer)}</small></span><span class="chat-row-meta">${c.unread?'<b>•</b>':''}</span>`;b.onclick=()=>openChat(c.id);b.oncontextmenu=e=>{e.preventDefault();activeChat=c.id;openChat(c.id);openMenu()};box.appendChild(b)})}
function renderMessages(){const c=chatById(activeChat);const box=$('#messages');if(!c){box.innerHTML='';return}box.innerHTML=(c.messages||[]).map(m=>`<div class="bubble-row ${m.mine?'mine':''}"><div class="bubble ${m.mine?'mine':''}">${m.file?`<div class="file-bubble">📎 <strong>${esc(m.file.name)}</strong><small>${esc(m.file.id)}</small></div>`:esc(m.text)}<time>${new Date(m.ts).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time></div></div>`).join('');box.scrollTop=box.scrollHeight;c.unread=0;save()}
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderChats()});
$('#new-chat').onclick=$('#new-chat-2').onclick=()=>{const uid=prompt('Enter AWE UID');if(uid)createChat(uid)};
function createChat(uid,name){uid=uid.trim();if(!/^AWE-[A-Z0-9]+$/i.test(uid)){toast('Invalid AWE UID');return}if(uid.toUpperCase()===db.uid.toUpperCase()){toast('That is your own UID');return}if(db.blocks.includes(uid))return toast('This UID is blocked');let c=db.chats.find(x=>x.peer===uid);if(!c){c={id:crypto.randomUUID(),peer:uid,name:name||uid,type:'direct',messages:[],unread:0,last:'New conversation',lastOpened:Date.now()};db.chats.unshift(c);db.contacts.unshift({uid,name:name||uid});save()}openChat(c.id)}

$('#message-form').onsubmit=e=>{e.preventDefault();const input=$('#message-input');const text=input.value.trim();if(!text||!activeChat)return;sendText(text);input.value=''};
function sendText(text){const c=chatById(activeChat);if(!c)return;c.messages.push({text,mine:true,ts:Date.now()});c.last=text;c.lastOpened=Date.now();save();renderMessages();if(dc?.readyState==='open')dc.send(JSON.stringify({t:'msg',text,ts:Date.now()}));}
$('#pick-file').onclick=()=>$('#file-input').click();$('#file-input').onchange=async e=>{const f=e.target.files?.[0];if(!f||!activeChat)return;const id='fid_'+await hashText(f.name+':'+f.size+':'+f.lastModified);const c=chatById(activeChat);c.messages.push({mine:true,ts:Date.now(),file:{name:f.name,id}});c.last='📎 '+f.name;save();renderMessages();if(dc?.readyState==='open')await sendFile(f,id);e.target.value=''};
async function hashText(s){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,32).toUpperCase()}
async function makeResource(kind,files){if(!files?.length)return;const sig=[...files].map(f=>f.name+':'+f.size+':'+f.lastModified).join('|');const id=kind.toLowerCase()+'_'+await hashText(sig+Date.now());const r={id,kind,created:Date.now(),name:files.length===1?files[0].name:(files[0].webkitRelativePath?.split('/')[0]||'Folder'),count:files.length};db.resources.unshift(r);save();renderResources();showId(r);return r}
$('#make-fid').onclick=()=>{$('#file-input').dataset.resource='FID';$('#file-input').click()};$('#make-pfid').onclick=()=>{$('#file-input').dataset.resource='PFID';$('#file-input').click()};$('#make-sid').onclick=()=>{$('#folder-input').dataset.resource='SID';$('#folder-input').click()};$('#make-psid').onclick=()=>{$('#folder-input').dataset.resource='PSID';$('#folder-input').click()};
$('#file-input').addEventListener('change',e=>{const k=e.target.dataset.resource;if(k)makeResource(k,e.target.files).then(()=>e.target.dataset.resource='');});$('#folder-input').addEventListener('change',e=>{const k=e.target.dataset.resource;if(k)makeResource(k,e.target.files).then(()=>e.target.dataset.resource='');});
$('#make-cfid').onclick=async()=>{const url=prompt('Paste a direct resource reference (FID/PFID/SID/PSID):');if(!url)return;const r={id:'cfid_'+await hashText(url),kind:'CFID',created:Date.now(),target:url};db.resources.unshift(r);save();renderResources();showId(r)};
function renderResources(){const box=$('#resource-list');box.innerHTML=db.resources.map(r=>`<button class="resource-line" data-r="${r.id}"><span>${r.kind==='PFID'||r.kind==='PSID'?'🔐':r.kind==='CFID'?'⚡':r.kind==='SID'?'🌐':'📄'}</span><span><strong>${esc(r.name||r.target||r.kind)}</strong><small>${esc(r.id)}</small></span><i>›</i></button>`).join('');$$('.resource-line').forEach(b=>b.onclick=()=>showId(db.resources.find(r=>r.id===b.dataset.r)))}
function showId(r){if(!r)return;$('#id-title').textContent=r.kind+' resource';$('#id-value').value=r.id;$('#id-details').textContent=JSON.stringify(r,null,2);$('#id-dialog').showModal()}
$('#id-close').onclick=()=>$('#id-dialog').close();$('#id-copy').onclick=()=>copy($('#id-value').value);

$('#create-channel').onclick=()=>{const name=prompt('Channel name');if(!name)return;const c={id:'ch_'+crypto.randomUUID().replaceAll('-',''),name,type:'channel',peer:'',messages:[],members:[db.uid],created:Date.now()};db.channels.unshift(c);db.chats.unshift({...c,id:'chat_'+c.id,last:'Channel created',lastOpened:Date.now()});save();renderChannels();renderChats();toast('Channel created locally')};
function renderChannels(){const box=$('#channel-list');box.innerHTML=db.channels.map(c=>`<div class="info-card"><span class="avatar orange">📢</span><div><strong>${esc(c.name)}</strong><small>${esc(c.id)} · ${c.members.length} member${c.members.length===1?'':'s'}</small></div><button class="ghost" data-invite="${c.id}">Invite</button></div>`).join('')||'<div class="empty-card">No channels yet.</div>';$$('[data-invite]').forEach(b=>b.onclick=()=>{const uid=prompt('Invite AWE UID');if(!uid)return;const c=db.channels.find(x=>x.id===b.dataset.invite);if(c&&!c.members.includes(uid))c.members.push(uid);save();toast('Invitation prepared for '+short(uid))})}
function renderPeople(){const box=$('#people-list');box.innerHTML=db.contacts.map(p=>`<div class="info-card"><span class="avatar purple">${esc(p.name?.[0]||'A')}</span><div><strong>${esc(p.name||p.uid)}</strong><small>${esc(p.uid)}</small></div><button class="ghost" data-person="${p.uid}">Chat</button><button class="ghost danger-lite" data-block="${p.uid}">Block</button></div>`).join('')||'<div class="empty-card">Search an AWE UID to add someone.</div>';$$('[data-person]').forEach(b=>b.onclick=()=>createChat(b.dataset.person));$$('[data-block]').forEach(b=>b.onclick=()=>blockPeer(b.dataset.block))}
function blockPeer(uid){if(!db.blocks.includes(uid))db.blocks.push(uid);db.chats=db.chats.filter(c=>c.peer!==uid);db.contacts=db.contacts.filter(c=>c.uid!==uid);save();activeChat=null;$('#conversation-empty').classList.remove('hidden');$('#conversation-content').classList.add('hidden');renderChats();renderPeople();toast('Blocked locally')}
$('#show-blocks').onclick=()=>alert(db.blocks.length?db.blocks.join('\n'):'No blocked IDs');
$('#chat-menu').onclick=openMenu;$('#chat-menu-close').onclick=()=>$('#chat-menu-dialog').close();
function openMenu(){$('#chat-menu-dialog').showModal()}
$('#delete-chat').onclick=()=>{if(!activeChat)return;db.chats=db.chats.filter(c=>c.id!==activeChat);save();activeChat=null;$('#chat-menu-dialog').close();$('#conversation-empty').classList.remove('hidden');$('#conversation-content').classList.add('hidden');renderChats()};
$('#block-chat').onclick=()=>{const c=chatById(activeChat);if(c)blockPeer(c.peer);$('#chat-menu-dialog').close()};
$('#rename-chat').onclick=()=>{const c=chatById(activeChat);if(c){const n=prompt('Name',c.name);if(n){c.name=n;save();renderChats();openChat(c.id)}}$('#chat-menu-dialog').close()};
$('#back-chats').onclick=()=>{$('#conversation-empty').classList.remove('hidden');$('#conversation-content').classList.add('hidden')};

async function connectPeer(){if(!activeChat)return toast('Open a chat first');if(pc)pc.close();pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});dc=pc.createDataChannel('awe');dc.onopen=()=>{$('#p2p-status').textContent='connected';toast('P2P connected')};dc.onmessage=e=>handleData(e.data);dc.onclose=()=>$('#p2p-status').textContent='disconnected';pc.ondatachannel=e=>{dc=e.channel;dc.onopen=()=>$('#p2p-status').textContent='connected';dc.onmessage=x=>handleData(x.data)};pc.onicecandidate=e=>{if(!e.candidate){const code=btoa(JSON.stringify(pc.localDescription));showSignal(code)}};const offer=await pc.createOffer();await pc.setLocalDescription(offer)}
$('#connect').onclick=connectPeer;
function showSignal(code){$('#signal-code').value=code;$('#signal-dialog').showModal()}
$('#signal-close').onclick=()=>$('#signal-dialog').close();$('#copy-signal').onclick=()=>copy($('#signal-code').value);
$('#paste-signal').onclick=async()=>{const code=prompt('Paste peer offer/answer code');if(!code)return;try{const obj=JSON.parse(atob(code));if(!pc){pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});pc.ondatachannel=e=>{dc=e.channel;dc.onopen=()=>$('#p2p-status').textContent='connected';dc.onmessage=x=>handleData(x.data)}}if(obj.type==='offer'){await pc.setRemoteDescription(obj);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);setTimeout(()=>showSignal(btoa(JSON.stringify(pc.localDescription))),500)}else{await pc.setRemoteDescription(obj);toast('Answer applied')}}catch{toast('Invalid connection code')}};
async function handleData(raw){try{const m=JSON.parse(raw);if(m.t==='msg'){const c=chatById(activeChat);if(!c)return;c.messages.push({text:m.text,mine:false,ts:m.ts||Date.now()});c.last=m.text;c.unread=(c.unread||0)+1;save();renderMessages()}if(m.t==='file-meta')toast('Incoming file: '+m.name)}catch{}}
async function sendFile(f,id){dc.send(JSON.stringify({t:'file-meta',id,name:f.name,size:f.size}));const chunk=64*1024;for(let p=0;p<f.size;p+=chunk){const buf=await f.slice(p,p+chunk).arrayBuffer();while(dc.bufferedAmount>1024*1024)await new Promise(r=>setTimeout(r,10));dc.send(buf)}}

async function startCall(kind){if(!activeChat)return toast('Open a chat first');$('#call-overlay').classList.remove('hidden');$('#call-title').textContent=kind==='video'?'Video call':kind==='screen'?'Screen sharing':'Voice call';$('#call-state').textContent='Waiting for peer connection';try{if(kind==='screen')localStream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});else localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:kind==='video'});$('#local-video').srcObject=localStream;toast('Media permission granted')}catch{toast('Permission was not granted')}}
$('#voice').onclick=()=>startCall('voice');$('#video').onclick=()=>startCall('video');$('#screen').onclick=()=>startCall('screen');$('#call-screen').onclick=()=>startCall('screen');$('#call-mute').onclick=()=>localStream?.getAudioTracks().forEach(t=>t.enabled=!t.enabled);$('#call-camera').onclick=()=>localStream?.getVideoTracks().forEach(t=>t.enabled=!t.enabled);function closeCall(){localStream?.getTracks().forEach(t=>t.stop());localStream=null;$('#local-video').srcObject=null;$('#call-overlay').classList.add('hidden')}$('#call-close').onclick=closeCall;$('#call-hangup').onclick=closeCall;
function renderCalls(){$('#call-history').innerHTML=db.calls.map(c=>`<div class="info-card"><span class="avatar purple">${esc(c.peer?.[4]||'A')}</span><div><strong>${esc(c.kind)}</strong><small>${esc(c.peer)} · ${new Date(c.ts).toLocaleString()}</small></div></div>`).join('')||'<div class="empty-card">No calls yet.</div>'}

function searchId(){const q=$('#global-search').value.trim();if(!q)return;const u=q.toUpperCase();if(/^AWE-/.test(u)){if(db.blocks.includes(u))return toast('This UID is blocked');createChat(u);showView('chats');return}const r=db.resources.find(x=>x.id.toUpperCase()===u||x.target===q);if(r){showId(r);return}const ch=db.channels.find(x=>x.id.toUpperCase()===u);if(ch){const c=db.chats.find(x=>x.peer===ch.id)||db.chats.find(x=>x.id==='chat_'+ch.id);if(c)openChat(c.id);showView('chats');return}toast('No local match. A UID alone cannot discover an offline peer without a rendezvous service.')}$('#global-search').onkeydown=e=>{if(e.key==='Enter')searchId()};$('#search-go').onclick=searchId;
$('#clear-data').onclick=()=>{if(confirm('Clear all local AWEP2PAWE data?')){localStorage.removeItem(KEY);location.reload()}};
renderChats();renderPeople();renderChannels();renderResources();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();