(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const toast=t=>{let x=$('#toast');if(!x){x=document.createElement('div');x.id='toast';x.className='toast';document.body.append(x)}x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),2200)};
function openView(v){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.classList.toggle('active-view',x.id==='view-'+v));}
function openChat(id,name='AWE User'){const S=window.S;if(!S)return;S.peerId=id;S.peerName=name;let rows=$('#chat-items');if(rows){let r=[...rows.querySelectorAll('.chat-row')].find(x=>x.dataset.chatId===id);if(!r){r=document.createElement('button');r.className='chat-row';r.dataset.chatId=id;r.dataset.chat=name;r.innerHTML=`<span class="avatar blue">${esc((name[0]||'A'))}</span><span class="chat-meta"><strong>${esc(name)}</strong><small>${esc(id)}</small></span><time>new</time>`;rows.prepend(r);r.onclick=()=>openChat(id,name)}[...rows.querySelectorAll('.chat-row')].forEach(x=>x.classList.toggle('selected',x===r));$('#conversation-name').textContent=name;const st=$('#p2p-status');if(st)st.textContent='AWE UID: '+id;openView('chats');}}
function searchResolve(q){q=q.trim();if(!q)return;const S=window.S||{};const contacts=S.contacts||[];const resources=S.resources||[];const rooms=S.rooms||[];let c=contacts.find(x=>x.id.toLowerCase()===q.toLowerCase());if(c){openChat(c.id,c.name||c.id);return}let r=resources.find(x=>String(x.id||x.fid||'').toLowerCase()===q.toLowerCase());if(r){openView('resources');toast('Resource found: '+q);return}let room=rooms.find(x=>String(x.id).toLowerCase()===q.toLowerCase());if(room){openView('chats');toast('Joined room: '+(room.name||q));return}if(/^awe1:[a-f0-9]{32,}$/i.test(q)||/^AWE1-[A-F0-9]{32,}$/i.test(q)){const id=q.toLowerCase().startsWith('awe1-')?'awe1:'+q.slice(5).toLowerCase():q.toLowerCase();openChat(id,id);toast('UID opened locally — connect to establish P2P');return}if(/^(fid|pfid|sid|psid)[_:]/i.test(q)){openView('resources');toast('Resource ID detected: '+q);return}toast('No local match for this ID');}
function setupSearch(){const input=$('#global-search');if(!input)return;input.placeholder='Search AWE UID, FID, PFID, SID, PSID, chats…';input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchResolve(input.value)}});let b=input.closest('.search');if(b&&!b.querySelector('.search-go')){const x=document.createElement('button');x.className='search-go';x.textContent='⌕';x.onclick=()=>searchResolve(input.value);b.append(x)}}
function setupButtons(){const plus=$('.composer .icon-btn');if(plus)plus.onclick=()=>openView('files');const smile=$$('.composer .icon-btn')[1];if(smile)smile.onclick=()=>{const i=$('#message-input');i.value+=' 🙂';i.focus()};const attach=$('#pick-file');if(attach)attach.onclick=()=>$('#file-input')?.click();$$('[data-action="create-resource"]').forEach(b=>b.onclick=()=>$('#resource-dialog')?.showModal());const nr=$('#new-resource');if(nr)nr.onclick=()=>$('#resource-dialog')?.showModal();}
function setupNav(){ $$('.nav-item').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view))); }
function mobileTabs(){if($('#mobile-tabs'))return;const n=document.createElement('nav');n.id='mobile-tabs';n.innerHTML='<button data-v="chats">💬<span>Chats</span></button><button data-v="contacts">👥<span>People</span></button><button data-v="resources">📦<span>Share</span></button><button data-v="calls">📞<span>Calls</span></button><button data-v="settings">⚙️<span>More</span></button>';document.body.append(n);n.onclick=e=>{const b=e.target.closest('button');if(b)openView(b.dataset.v)}}
function lightFirst(){const S=window.S;if(S&&S.theme==='dark'&&!localStorage.getItem('awe_theme')){S.theme='light';localStorage.setItem('awe_theme','light')}document.documentElement.dataset.theme=(S&&S.theme)||'light';$$('[data-theme]').forEach(b=>b.onclick=()=>{const t=b.dataset.theme;document.documentElement.dataset.theme=t;if(window.S)window.S.theme=t;localStorage.setItem('awe_theme',t);$$('[data-theme]').forEach(x=>x.classList.toggle('active',x.dataset.theme===t))})}
addEventListener('DOMContentLoaded',()=>setTimeout(()=>{setupSearch();setupButtons();setupNav();mobileTabs();lightFirst();},120));
})();
