(()=>{'use strict';
const STATE='AWEP2PAWE_STATE_V11';
const load=()=>{try{return JSON.parse(localStorage.getItem(STATE)||'{}')}catch{return {}}};
const save=s=>localStorage.setItem(STATE,JSON.stringify(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=t=>{const e=document.querySelector('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__aweActionToast);window.__aweActionToast=setTimeout(()=>e.classList.remove('show'),2200)};
let activeMessage=null;
function state(){const s=load();s.chats||=[];s.blocks||[];return s}
function activeChat(s){const row=document.querySelector('.chat-row.selected');const id=row?.dataset.chat;if(id)return s.chats.find(c=>c.id===id);return s.chats.find(c=>c.id===window.__aweActiveChat)}
function messageFromElement(s,el){const bubble=el.closest('.bubble-row');if(!bubble)return null;const rows=[...document.querySelectorAll('#messages .bubble-row')];const i=rows.indexOf(bubble);const c=activeChat(s);return c&&i>=0?{chat:c,index:i,msg:c.messages[i]}:null}
function actionMenu(target){document.querySelector('#message-action-menu')?.remove();const s=state(),x=messageFromElement(s,target);if(!x)return;activeMessage=x;const m=document.createElement('div');m.id='message-action-menu';m.className='message-action-menu';m.setAttribute('role','menu');const actions=[['reply','↩ Reply'],['forward','↗ Forward'],['copy','⧉ Copy'],['edit','✏ Edit'],['delete','🗑 Delete'],['mark','✓ Mark read']];m.innerHTML=actions.map(([a,t])=>`<button type="button" data-message-action="${a}">${t}</button>`).join('');document.body.append(m);const r=target.getBoundingClientRect();m.style.left=Math.max(8,Math.min(innerWidth-190,r.left))+'px';m.style.top=Math.min(innerHeight-250,r.bottom+6)+'px'}
function rerender(){const s=state();const c=activeMessage?.chat||activeChat(s);if(!c)return;const b=document.querySelector('#messages');if(!b)return;b.innerHTML=(c.messages||[]).map(m=>`<div class="bubble-row ${m.mine?'mine':''}" data-message-id="${esc(m.id)}"><div class="bubble ${m.mine?'mine':''}">${m.replyTo?`<small class="reply-ref">↩ ${esc(m.replyTo.text||'message')}</small>`:''}${m.file?`📎 <strong>${esc(m.file.name)}</strong><small>${esc(m.file.id)} · ${Math.ceil(m.file.size/1024)} KB</small>`:esc(m.text||'')}<time>${new Date(m.ts).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} · ${esc(m.delivery||'queued')}</time></div></div>`).join('');b.scrollTop=b.scrollHeight;attachMessageHandlers()}
function perform(a){const s=state(),x=activeMessage;if(!x)return;const m=x.chat.messages[x.index];if(!m){toast('Message no longer exists');return}if(a==='copy'){navigator.clipboard?.writeText(m.text||'').then(()=>toast('Message copied')).catch(()=>toast('Clipboard unavailable'));return}if(a==='delete'){x.chat.messages.splice(x.index,1);x.chat.last=x.chat.messages.at(-1)?.text||'No messages';x.chat.updated=Date.now();save();rerender();return}if(a==='edit'){if(!m.mine||!m.text){toast('Only your text messages can be edited');return}const n=prompt('Edit message',m.text);if(n?.trim()&&n.trim()!==m.text){m.text=n.trim();m.edited=true;m.editedAt=Date.now();x.chat.updated=Date.now();save();rerender();if(window.__aweSendControl)window.__aweSendControl({kind:'message-edit',id:m.id,text:m.text,editedAt:m.editedAt})}return}if(a==='reply'){const i=document.querySelector('#message-input');if(i){i.value=`↩ ${m.text||m.file?.name||'message'}\n`;i.focus();i.dataset.replyTo=m.id;toast('Reply target selected')}return}if(a==='forward'){const uid=prompt('Forward to AWE UID');if(uid){const targetChat=s.chats.find(c=>c.peer?.toUpperCase()===uid.trim().toUpperCase());if(targetChat){const copy={...m,id:crypto.randomUUID(),ts:Date.now(),mine:true,forwarded:true,delivery:'queued'};targetChat.messages.push(copy);targetChat.last=copy.text||'Forwarded message';targetChat.updated=Date.now();save();toast('Forwarded locally');}else toast('Open the target UID first')}}if(a==='mark'){m.read=true;m.unread=false;save();rerender()}}
function attachMessageHandlers(){document.querySelectorAll('#messages .bubble-row').forEach(e=>{e.addEventListener('contextmenu',ev=>{ev.preventDefault();actionMenu(e)});e.addEventListener('click',ev=>{if(ev.detail===2)actionMenu(e)})})}
function patchComposer(){const f=document.querySelector('#message-form');if(!f||f.dataset.actionsBound)return;f.dataset.actionsBound='1';f.addEventListener('submit',()=>{const i=document.querySelector('#message-input');if(i?.dataset.replyTo){setTimeout(()=>delete i.dataset.replyTo,0)}});}
document.addEventListener('click',e=>{const a=e.target.closest('[data-message-action]');if(a){e.stopPropagation();perform(a.dataset.messageAction);document.querySelector('#message-action-menu')?.remove();return}if(!e.target.closest('#message-action-menu')&&!e.target.closest('#messages .bubble-row'))document.querySelector('#message-action-menu')?.remove()});
addEventListener('DOMContentLoaded',()=>setTimeout(()=>{patchComposer();attachMessageHandlers()},250));
})();
