(()=>{'use strict';
const $=s=>document.querySelector(s);
const R=new Map(); let room=null; let scanning=false;
const rnd=n=>crypto.getRandomValues(new Uint8Array(n));
const b64=u=>{let s='';u=new Uint8Array(u);for(let i=0;i<u.length;i+=0x8000)s+=String.fromCharCode(...u.subarray(i,i+0x8000));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
const ub64=s=>{s=s.replace(/-/g,'+').replace(/_/g,'/');s+='='.repeat((4-s.length%4)%4);const x=atob(s),u=new Uint8Array(x.length);for(let i=0;i<x.length;i++)u[i]=x.charCodeAt(i);return u};
const toast=m=>{const e=$('#toast');if(e){e.textContent=m;e.classList.add('show');clearTimeout(window.__aweMultiToast);window.__aweMultiToast=setTimeout(()=>e.classList.remove('show'),2400)}};
const pack=o=>'awemesh1:'+b64(new TextEncoder().encode(JSON.stringify({v:1,p:'AWE-MESH',...o})));
const unpack=s=>{try{if(!s.startsWith('awemesh1:'))return null;const o=JSON.parse(new TextDecoder().decode(ub64(s.slice(9))));return o.v===1&&o.p==='AWE-MESH'?o:null}catch{return null}};
const rtc=()=>new RTCPeerConnection({iceServers:[{urls:'stun:stun.cloudflare.com:3478'},{urls:'stun:stun.l.google.com:19302'}]});
const gather=pc=>new Promise(r=>{if(pc.iceGatheringState==='complete')return r();let done=false;const f=()=>{if(done)return;done=true;clearTimeout(t);r()};const t=setTimeout(f,6000);pc.onicegatheringstatechange=()=>pc.iceGatheringState==='complete'&&f()});
const code=()=>{const a=rnd(5);return 'M-'+Array.from(a,x=>x.toString(36).padStart(2,'0')).join('').slice(0,10).toUpperCase()};
function ensureRoom(){if(room)return room;room={id:code(),host:true};return room}
function showChat(){document.body.classList.add('in-chat');$('#home')?.classList.add('hidden');$('#chat')?.classList.remove('hidden')}
function addBubble(text,mine=false){const b=$('#messages');if(!b)return;const e=document.createElement('div');e.className='bubble '+(mine?'mine':'');e.textContent=text;b.appendChild(e);b.scrollTop=b.scrollHeight}
function setRoomUI(){if(!room)return;$('#chat-id').textContent=room.id;$('#short-id').textContent=room.id;$('#peer-state').textContent=`Mesh • ${R.size+1} participant${R.size===0?'':'s'}`}
function qr(text,label){const box=$('#qr');if(!box||typeof qrcode!=='function')return;box.innerHTML='';try{const q=qrcode(0,'M');q.addData(text,'Byte');q.make();box.innerHTML=q.createSvgTag(5,4);$('#qr-status').textContent=label;$('#download-qr').disabled=false;window.__aweMultiLastQr=text}catch{toast('Invite QR too large')}}
function bindPeer(p){p.pc.ondatachannel=e=>{p.dc=e.channel;wire(p)};if(p.dc)wire(p);p.pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(p.pc.connectionState)){R.delete(p.id);setRoomUI()}}}
function wire(p){if(p.wired)return;p.wired=true;p.dc.onopen=()=>{setRoomUI();showChat();toast(`Peer ${p.id} connected`)};p.dc.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.t==='chat'){addBubble(m.text,false);if(room?.host)for(const [id,q] of R)if(id!==p.id&&q.dc?.readyState==='open')q.dc.send(JSON.stringify(m))}}catch{}}}
async function createInvite(){ensureRoom();room.host=true;showChat();setRoomUI();$('#peer-state').textContent=`Mesh • ${R.size+1} participant • waiting for scans`;const payload=pack({type:'invite',room:room.id,exp:Date.now()+300000});qr(payload,`Chat ${room.id} • invite`);toast('Invite QR ready — scan to join chat')}
async function joinInvite(o){if(Date.now()>o.exp)return toast('Invite expired');room={id:o.room,host:false};showChat();setRoomUI();$('#peer-state').textContent='Opening chat • preparing secure connection…';const pc=rtc();const offer=await pc.createOffer({offerToReceiveAudio:false,offerToReceiveVideo:false});await pc.setLocalDescription(offer);await gather(pc);const p={id:'__host',pc,dc:null,initiator:true};R.set('__host',p);pc.ondatachannel=e=>{p.dc=e.channel;wire(p)};const payload=pack({type:'join-offer',room:o.room,sdp:pc.localDescription.sdp,exp:Date.now()+300000});qr(payload,`Chat ${room.id} • connection QR`);showChat();setRoomUI();toast('Chat opened immediately • show connection QR to host')}
async function hostAcceptJoin(o){if(!room?.host||o.room!==room.id)return toast('Wrong chat');showChat();setRoomUI();$('#peer-state').textContent='Adding participant • preparing secure connection…';const guestId=code(),pc=rtc();const p={id:guestId,pc,dc:pc.createDataChannel('mesh',{ordered:true,maxRetransmits:null}),initiator:false};R.set(guestId,p);bindPeer(p);await pc.setRemoteDescription({type:'offer',sdp:o.sdp});const a=await pc.createAnswer();await pc.setLocalDescription(a);await gather(pc);qr(pack({type:'join-answer',room:room.id,peerId:guestId,sdp:pc.localDescription.sdp,exp:Date.now()+300000}),`Chat ${room.id} • connection answer`);showChat();setRoomUI();toast('Participant added • scan answer to finish connection')}
async function finishJoinAnswer(o){if(!room||room.host||o.room!==room.id)return toast('Wrong chat answer');const p=R.get('__host');if(!p)return toast('Join session expired');showChat();$('#peer-state').textContent='Connecting securely…';await p.pc.setRemoteDescription({type:'answer',sdp:o.sdp});showChat();setRoomUI();toast('Chat connection started')}
function sendAll(text){const m=JSON.stringify({t:'chat',text});let sent=0;for(const p of R.values())if(p.dc?.readyState==='open'){try{p.dc.send(m);sent++}catch{}}if(sent)addBubble(text,true);else toast('No mesh peers connected')}
function installScanner(){if($('#awe-mesh-scanner'))return;const d=document.createElement('dialog');d.id='awe-mesh-scanner';d.innerHTML='<div class="modal"><button class="close" id="awe-mesh-close">×</button><h2>Scan chat QR</h2><p>Processed locally in this browser.</p><video id="awe-mesh-video" autoplay muted playsinline></video><div class="modal-actions"><button class="ghost" id="awe-mesh-image">Choose QR image</button></div><input id="awe-mesh-file" type="file" accept="image/*" hidden></div>';document.body.appendChild(d);$('#awe-mesh-close').onclick=()=>{stopScan();d.close()};$('#awe-mesh-image').onclick=()=>$('#awe-mesh-file').click();$('#awe-mesh-file').onchange=async e=>{const f=e.target.files[0];if(f)await scanImage(f)}}
function stopScan(){const v=$('#awe-mesh-video');v?.srcObject?.getTracks().forEach(t=>t.stop());if(v)v.srcObject=null;scanning=false}
async function startScan(){installScanner();const d=$('#awe-mesh-scanner'),v=$('#awe-mesh-video');if(!navigator.mediaDevices?.getUserMedia||!('BarcodeDetector'in window))return toast('QR camera scanner unavailable; use the main scanner or choose an image');d.showModal();scanning=true;try{v.srcObject=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:960},height:{ideal:540}},audio:false});const detector=new BarcodeDetector({formats:['qr_code']});const loop=async()=>{if(!scanning||!d.open)return stopScan();try{const z=await detector.detect(v),raw=z[0]?.rawValue;if(raw){stopScan();d.close();await handleQR(raw);return}}catch{}requestAnimationFrame(loop)};loop()}catch{stopScan();d.close();toast('Camera permission denied')}}
async function scanImage(f){try{const img=await createImageBitmap(f),z=await new BarcodeDetector({formats:['qr_code']}).detect(img);img.close();const raw=z[0]?.rawValue;if(!raw)return toast('No QR found');$('#awe-mesh-scanner').close();await handleQR(raw)}catch{toast('Could not read QR image')}}
async function handleQR(raw){const o=unpack(raw);if(!o)return toast('Not an AWE mesh QR');if(o.type==='invite')return joinInvite(o);if(o.type==='join-offer'&&room?.host)return hostAcceptJoin(o);if(o.type==='join-answer')return finishJoinAnswer(o);toast('Unsupported mesh QR')}
function hook(){installScanner();const qrBtn=$('#chat-qr');qrBtn?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();createInvite()},true);const head=$('.chat-head .call-actions');if(head&&!$('#mesh-scan')){const b=document.createElement('button');b.id='mesh-scan';b.className='icon';b.title='Join chat QR';b.textContent='⌕';b.onclick=startScan;head.insertBefore(b,head.firstChild)}const form=$('#composer');form?.addEventListener('submit',e=>{if(!room||R.size===0)return;e.preventDefault();e.stopImmediatePropagation();const input=$('#message'),t=input.value.trim();if(t){sendAll(t);input.value=''}},true);window.__aweMesh={createInvite,startScan,handleQR,sendAll}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook,{once:true});else hook();
})();