(()=>{'use strict';
const DB='AWEP2PAWE_RESOURCE_V2', STORE='resources', CHUNK=1024*1024;
const $=s=>document.querySelector(s); const toast=t=>{const e=$('#toast');if(e){e.textContent=t;e.classList.add('show');clearTimeout(window.__aweToast);window.__aweToast=setTimeout(()=>e.classList.remove('show'),2200)}};
const enc=new TextEncoder();
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function hash(data){return hex(await crypto.subtle.digest('SHA-256',data))}
async function hashFile(file){const h=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return hex(h)}
function db(){return new Promise((ok,no)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'})};q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function put(r){const d=await db();return new Promise((ok,no)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(r);t.oncomplete=()=>{d.close();ok()};t.onerror=()=>{d.close();no(t.error)}})}
async function get(id){const d=await db();return new Promise((ok,no)=>{const t=d.transaction(STORE,'readonly');const q=t.objectStore(STORE).get(id);q.onsuccess=()=>{d.close();ok(q.result)};q.onerror=()=>{d.close();no(q.error)}})}
function id(prefix,seed){return prefix+'-'+seed.slice(0,40).toUpperCase()}
async function derive(password,salt){const base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptFile(file,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derive(password,salt);const plain=new Uint8Array(await file.arrayBuffer());const cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain));return {salt:[...salt],iv:[...iv],cipher:Array.from(cipher),size:file.size,mime:file.type||'application/octet-stream',name:file.name}}
function show(r){const d=$('#id-dialog'),v=$('#id-value'),det=$('#id-details'),title=$('#id-title');if(!d)return;title.textContent=r.kind;v.value=r.id;det.textContent=JSON.stringify({id:r.id,kind:r.kind,name:r.name,size:r.size,hash:r.hash,files:r.files?.length||undefined},null,2);d.showModal()}
async function saveResource(kind,files,password){if(!files.length)return;const first=files[0];const list=[];for(const f of files){list.push({name:f.webkitRelativePath||f.name,size:f.size,type:f.type||'application/octet-stream',hash:await hashFile(f)})}const seed=await hash(enc.encode(JSON.stringify(list)));const rid=id(kind,seed);let payload={id:rid,kind,name:first.name,size:first.size,hash:list.length===1?list[0].hash:seed,files:list,created:Date.now(),owner:location.origin};if(password){payload.private=true;payload.encrypted=await encryptFile(first,password)}else if(list.length===1){payload.mime=first.type;payload.bytes=Array.from(new Uint8Array(await first.arrayBuffer()))}await put(payload);show(payload);toast(kind+' created locally');return payload}
async function choose(kind,folder=false,privateResource=false){const input=folder?$('#folder-input'):$('#file-input');if(!input)return;input.value='';input.onchange=async()=>{const files=[...input.files];if(!files.length)return;let password=null;if(privateResource){password=prompt('Create a password for this private resource');if(!password)return toast('Cancelled');const again=prompt('Repeat password');if(password!==again)return toast('Passwords do not match')}await saveResource(kind,files,password)};input.click()}
$('#make-fid')?.addEventListener('click',()=>choose('FID'));$('#make-pfid')?.addEventListener('click',()=>choose('PFID',false,true));$('#make-sid')?.addEventListener('click',()=>choose('SID',true));$('#make-psid')?.addEventListener('click',()=>choose('PSID',true,true));
$('#id-copy')?.addEventListener('click',async()=>{const v=$('#id-value')?.value;if(v){try{await navigator.clipboard.writeText(v);toast('ID copied')}catch{}}});$('#id-close')?.addEventListener('click',()=>$('#id-dialog')?.close());
window.AWEResources={get,hashFile,saveResource,CHUNK};
})();