(()=>{'use strict';
const DB='AWEP2PAWE_RESOURCE_V3',META='resources',CHUNKS='chunks',CHUNK=1024*1024;
const $=s=>document.querySelector(s),enc=new TextEncoder();
const toast=t=>{const e=$('#toast');if(e){e.textContent=t;e.classList.add('show');clearTimeout(window.__aweToast);window.__aweToast=setTimeout(()=>e.classList.remove('show'),2200)}};
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function hash(data){return hex(await crypto.subtle.digest('SHA-256',new Uint8Array(data)))}
async function hashFile(file){return hash(await file.arrayBuffer())}
function db(){return new Promise((ok,no)=>{const q=indexedDB.open(DB,2);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains(META))d.createObjectStore(META,{keyPath:'id'});if(!d.objectStoreNames.contains(CHUNKS))d.createObjectStore(CHUNKS,{keyPath:'key'})};q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function tx(store,mode,fn){const d=await db();return new Promise((ok,no)=>{const t=d.transaction(store,mode),s=t.objectStore(store);try{fn(s,t)}catch(e){d.close();no(e);return}t.oncomplete=()=>{d.close();ok()};t.onerror=()=>{d.close();no(t.error)}})}
async function putMeta(r){return tx(META,'readwrite',s=>s.put(r))}
async function readMeta(id){const d=await db();return new Promise((ok,no)=>{const q=d.transaction(META,'readonly').objectStore(META).get(id);q.onsuccess=()=>{d.close();ok(q.result)};q.onerror=()=>{d.close();no(q.error)}})}
async function putChunk(key,data){return tx(CHUNKS,'readwrite',s=>s.put({key,data:data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength)}))}
async function readChunk(key){const d=await db();return new Promise((ok,no)=>{const q=d.transaction(CHUNKS,'readonly').objectStore(CHUNKS).get(key);q.onsuccess=()=>{d.close();ok(q.result?.data?new Uint8Array(q.result.data):null)};q.onerror=()=>{d.close();no(q.error)}})}
async function deleteResource(id){const d=await db();return new Promise((ok,no)=>{const t=d.transaction([META,CHUNKS],'readwrite'),m=t.objectStore(META),s=t.objectStore(CHUNKS);m.delete(id);const q=s.openCursor();q.onsuccess=()=>{const c=q.result;if(!c)return;if(String(c.key).startsWith(id+':'))c.delete();c.continue()};t.oncomplete=()=>{d.close();ok(true)};t.onerror=()=>{d.close();no(t.error)}})}
async function derive(password,salt){if(typeof password!=='string'||password.length<8)throw Error('Password must contain at least 8 characters');const base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function chunkFile(file,temp,index,key,privateMode){const start=index*CHUNK,end=Math.min(file.size,start+CHUNK),plain=new Uint8Array(await file.slice(start,end).arrayBuffer());const digest=await hash(plain);let data=plain,iv=null;if(privateMode){iv=crypto.getRandomValues(new Uint8Array(12));data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain))}await putChunk(`${temp}:${index}`,data);return {index,size:plain.length,hash:digest,iv:iv?[...iv]:null,storedSize:data.length}}
async function storeFile(file,temp,key,privateMode){const chunks=[];for(let i=0;i<Math.max(1,Math.ceil(file.size/CHUNK));i++)chunks.push(await chunkFile(file,temp,i,key,privateMode));return {name:file.webkitRelativePath||file.name,size:file.size,type:file.type||'application/octet-stream',hash:await hashFile(file),chunks}}
async function moveChunks(tempPrefix,id){return tx(CHUNKS,'readwrite',(s)=>{const q=s.openCursor();q.onsuccess=()=>{const c=q.result;if(!c)return;const k=String(c.key);if(k.startsWith(tempPrefix+':')){const next=id+k.slice(tempPrefix.length);s.put({key:next,data:c.value.data});c.delete()}c.continue()}})}
async function createResource(kind,files,password){if(!files?.length)throw Error('A file or folder is required');const privateMode=kind==='PFID'||kind==='PSID';let key=null,salt=null;if(privateMode){salt=crypto.getRandomValues(new Uint8Array(16));key=await derive(password,salt)}const manifest=[];const temps=[];for(const f of files){const temp=`tmp-${crypto.randomUUID()}`;temps.push(temp);manifest.push(await storeFile(f,temp,key,privateMode))}const canonical=JSON.stringify(manifest.map(x=>[x.name,x.size,x.type,x.hash,x.chunks.map(c=>c.hash)]));const seed=await hash(enc.encode(canonical)),id=`${kind}-${seed.slice(0,40).toUpperCase()}`;for(const temp of temps)await moveChunks(temp,id);for(const f of manifest)for(const c of f.chunks)c.key=id+':'+c.index;const meta={id,kind,version:3,name:manifest[0].name,size:manifest.reduce((n,x)=>n+x.size,0),hash:seed,files:manifest,private:privateMode,salt:salt?[...salt]:null,created:Date.now(),owner:localStorage.getItem('awep2p:local')||null};await putMeta(meta);show(meta);toast(kind+' created locally');return meta}
async function readResource(id,password){const r=await readMeta(id);if(!r)throw Error('Resource not found locally');let key=null;if(r.private){if(!password)throw Error('Password required');key=await derive(password,new Uint8Array(r.salt))}const out=[];for(const f of r.files){const parts=[];for(const c of f.chunks){const stored=await readChunk(`${id}:${c.index}`);if(!stored)throw Error('Resource chunk missing');let plain=stored;if(r.private)plain=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(c.iv)},key,stored));if(await hash(plain)!==c.hash)throw Error('Resource chunk integrity failed');parts.push(plain)}const blob=new Blob(parts,{type:f.type});if(await hash(await blob.arrayBuffer())!==f.hash)throw Error('File integrity verification failed');out.push({name:f.name,type:f.type,size:f.size,blob,hash:f.hash})}return out}
function show(r){const d=$('#id-dialog'),v=$('#id-value'),det=$('#id-details'),title=$('#id-title');if(!d)return;title.textContent=r.kind;v.value=r.id;det.textContent=JSON.stringify({id:r.id,kind:r.kind,name:r.name,size:r.size,hash:r.hash,files:r.files?.length||0,private:r.private},null,2);d.showModal()}
async function choose(kind,folder=false,privateResource=false){const input=folder?$('#folder-input'):$('#file-input');if(!input)return;input.value='';input.onchange=async()=>{try{const files=[...input.files];if(!files.length)throw Error('Select a file or folder');let password=null;if(privateResource){password=prompt('Create a password (minimum 8 characters)');if(password===null)return;const again=prompt('Repeat password');if(password!==again)throw Error('Passwords do not match')}await createResource(kind,files,password)}catch(e){toast(e.message||'Resource creation failed')}};input.click()}
$('#make-fid')?.addEventListener('click',()=>choose('FID'));$('#make-pfid')?.addEventListener('click',()=>choose('PFID',false,true));$('#make-sid')?.addEventListener('click',()=>choose('SID',true));$('#make-psid')?.addEventListener('click',()=>choose('PSID',true,true));$('#id-copy')?.addEventListener('click',async()=>{const v=$('#id-value')?.value;if(v)try{await navigator.clipboard.writeText(v);toast('ID copied')}catch{}});$('#id-close')?.addEventListener('click',()=>$('#id-dialog')?.close());
window.AWEResources={get:readMeta,read:readResource,hashFile,create:createResource,delete:deleteResource,readChunk,CHUNK};
})();