(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='AWEP2PAWE_STATE_V10', CHUNK=48*1024, LANGS={en:{chats:'Chats',people:'People',channels:'Channels',resources:'Resources',calls:'Calls',settings:'Settings',search:'Search UID, FID, PFID, SID, PSID or CFID…',newchat:'New chat',write:'Write a message…'},hy:{chats:'Չատեր',people:'Մարդիկ',channels:'Ալիքներ',resources:'Ռեսուրսներ',calls:'Զանգեր',settings:'Կարգավորումներ',search:'Որոնել UID, FID, PFID, SID, PSID կամ CFID…',newchat:'Նոր չատ',write:'Գրել հաղորդագրություն…'},ru:{chats:'Чаты',people:'Люди',channels:'Каналы',resources:'Ресурсы',calls:'Звонки',settings:'Настройки',search:'Поиск UID, FID, PFID, SID, PSID или CFID…',newchat:'Новый чат',write:'Сообщение…'},es:{chats:'Chats',people:'Personas',channels:'Canales',resources:'Recursos',calls:'Llamadas',settings:'Ajustes',search:'Buscar UID, FID, PFID, SID, PSID o CFID…',newchat:'Nuevo chat',write:'Escribe un mensaje…'},fr:{chats:'Discussions',people:'Personnes',channels:'Canaux',resources:'Ressources',calls:'Appels',settings:'Réglages',search:'Rechercher UID, FID, PFID, SID, PSID ou CFID…',newchat:'Nouvelle discussion',write:'Écrire un message…'},de:{chats:'Chats',people:'Personen',channels:'Kanäle',resources:'Ressourcen',calls:'Anrufe',settings:'Einstellungen',search:'AWE UID, FID, PFID, SID, PSID oder CFID suchen…',newchat:'Neuer Chat',write:'Nachricht schreiben…'},pt:{chats:'Chats',people:'Pessoas',channels:'Canais',resources:'Recursos',calls:'Chamadas',settings:'Definições',search:'Pesquisar UID, FID, PFID, SID, PSID ou CFID…',newchat:'Novo chat',write:'Escreva uma mensagem…'},ar:{chats:'المحادثات',people:'الأشخاص',channels:'القنوات',resources:'الموارد',calls:'المكالمات',settings:'الإعدادات',search:'ابحث عن UID أو FID أو PFID أو SID أو PSID أو CFID…',newchat:'محادثة جديدة',write:'اكتب رسالة…'},hi:{chats:'चैट',people:'लोग',channels:'चैनल',resources:'संसाधन',calls:'कॉल',settings:'सेटिंग्स',search:'UID, FID, PFID, SID, PSID या CFID खोजें…',newchat:'नई चैट',write:'संदेश लिखें…'},zh:{chats:'聊天',people:'联系人',channels:'频道',resources:'资源',calls:'通话',settings:'设置',search:'搜索 UID、FID、PFID、SID、PSID 或 CFID…',newchat:'新聊天',write:'输入消息…'},tr:{chats:'Sohbetler',people:'Kişiler',channels:'Kanallar',resources:'Kaynaklar',calls:'Aramalar',settings:'Ayarlar',search:'UID, FID, PFID, SID, PSID veya CFID ara…',newchat:'Yeni sohbet',write:'Mesaj yaz…'},fa:{chats:'گفتگوها',people:'افراد',channels:'کانال‌ها',resources:'منابع',calls:'تماس‌ها',settings:'تنظیمات',search:'جستجوی UID، FID، PFID، SID، PSID یا CFID…',newchat:'گفتگوی جدید',write:'پیام بنویسید…'}};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=t=>{const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__aweToast);window.__aweToast=setTimeout(()=>e.classList.remove('show'),2400)};
const copy=async t=>{try{await navigator.clipboard.writeText(t);toast('Copied')}catch{prompt('Copy',t)}};
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
let st=load(); st.uid ||= 'AWE-'+crypto.randomUUID().replaceAll('-','').slice(0,24).toUpperCase(); st.chats ||= [];st.contacts ||= [];st.channels ||= [];st.resources ||= [];st.blocks ||= [];st.calls ||= [];st.lang ||= 'en';st.theme ||= 'light';
const save=()=>localStorage.setItem(KEY,JSON.stringify(st));
let active=null, pc=null, dc=null, localStream=null, remoteStream=null, rx=new Map();
$('#identity-id').textContent=st.uid;$('#settings-id').textContent=st.uid;document.body.className=st.theme;
function applyLang(){const l=LANGS[st.lang]||LANGS.en;document.documentElement.lang=st.lang;[['chats',l.chats],['contacts',l.people],['channels',l.channels],['resources',l.resources],['calls',l.calls],['settings',l.settings]].forEach(([v,t])=>$$(`[data-view="${v}"] span`).forEach(e=>e.textContent=t));if($('#global-search'))$('#global-search').placeholder=l.search;if($('#message-input'))$('#message-input').placeholder=l.write;const n=$('#new-chat');if(n)n.textContent='＋ '+l.newchat}
applyLang();
function view(v){$$('.view').forEach(e=>e.classList.toggle('active-view',e.id==='view-'+v));$$('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view===v));if(v==='chats')renderChats();if(v==='contacts')renderPeople();if(v==='channels')renderChannels();if(v==='resources')renderResources();if(v==='calls')renderCalls()}
$$('[data-view]').forEach(e=>e.onclick=()=>view(e.dataset.view));
$('#theme-light')?.addEventListener('click',()=>{st.theme='light';document.body.className='light';save()});$('#theme-dark')?.addEventListener('click',()=>{st.theme='dark';document.body.className='dark';save()});
$('#copy-uid')?.addEventListener('click',()=>copy(st.uid));$('#copy-uid-2')?.addEventListener('click',()=>copy(st.uid));
function chatForPeer(uid,name){uid=uid.trim().toUpperCase();if(!/^AWE-[A-Z0-9]+$/.test(uid))return toast('Invalid AWE UID');if(uid===st.uid)return toast('This is your UID');if(st.blocks.includes(uid))return toast('Blocked UID');let c=st.chats.find(x=>x.peer===uid&&x.type==='direct');if(!c){c={id:crypto.randomUUID(),peer:uid,name:name||uid,type:'direct',messages:[],unread:0,last:'New conversation',updated:Date.now()};st.chats.unshift(c);if(!st.contacts.some(x=>x.uid===uid))st.contacts.unshift({uid,name:name||uid});save()}openChat(c.id);return c}
function openChat(id){const c=st.chats.find(x=>x.id===id);if(!c||st.blocks.includes(c.peer))return;active=id;c.unread=0;c.updated=Date.now();save();$('#conversation-empty').classList.add('hidden');$('#conversation-content').classList.remove('hidden');$('#conversation-name').textContent=c.name||c.peer;$('#conversation-avatar').textContent=(c.name||c.peer).slice(0,1).toUpperCase();$('#p2p-status').textContent=dc?.readyState==='open'?'connected':'offline';renderChats();renderMessages()}
function renderChats(){const b=$('#chat-items');if(!b)return;let f=document.querySelector('.filter.active')?.dataset.filter||'all';let a=st.chats.filter(c=>f==='all'||f==='unread'&&c.unread||f==='groups'&&(c.type==='group'||c.type==='channel'));a.sort((x,y)=>(y.updated||0)-(x.updated||0));b.innerHTML=a.map(c=>`<button class="chat-row ${c.id===active?'selected':''}" data-chat="${c.id}"><span class="avatar purple">${esc((c.name||c.peer||'A')[0].toUpperCase())}</span><span class="chat-meta"><strong>${esc(c.name||c.peer)}</strong><small>${esc(c.last||'')}</small></span>${c.unread?`<b class="unread-dot">${Math.min(99,c.unread)}</b>`:''}</button>`).join('');$('#chat-empty').style.display=a.length?'none':'flex';$$('[data-chat]').forEach(e=>e.onclick=()=>openChat(e.dataset.chat))}
function renderMessages(){const c=st.chats.find(x=>x.id===active),b=$('#messages');if(!b)return;b.innerHTML=(c?.messages||[]).map(m=>`<div class="bubble-row ${m.mine?'mine':''}"><div class="bubble ${m.mine?'mine':''}">${m.file?`📎 <strong>${esc(m.file.name)}</strong><small>${esc(m.file.id)} · ${Math.ceil(m.file.size/1024)} KB</small>`:esc(m.text||'')}<time>${new Date(m.ts).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time></div></div>`).join('');b.scrollTop=b.scrollHeight}
function addMsg(c,m){c.messages.push(m);c.last=m.file?'📎 '+m.file.name:(m.text||'');c.updated=Date.now();save();renderMessages();renderChats()}
function sendPacket(o){if(dc?.readyState==='open')dc.send(JSON.stringify(o))}
function sendText(t){const c=st.chats.find(x=>x.id===active);if(!c)return;if(st.blocks.includes(c.peer))return toast('Blocked');const m={t:'msg',id:crypto.randomUUID(),text:t,ts:Date.now(),from:st.uid};addMsg(c,{...m,mine:true});sendPacket(m)}
$('#message-form')?.addEventListener('submit',e=>{e.preventDefault();const i=$('#message-input'),t=i.value.trim();if(t){sendText(t);i.value=''}});
$$('.filter').forEach(e=>e.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));e.classList.add('active');renderChats()});
$('#new-chat')?.addEventListener('click',()=>{const x=prompt('AWE UID');if(x)chatForPeer(x)});$('#new-chat-2')?.addEventListener('click',()=>{const x=prompt('AWE UID');if(x)chatForPeer(x)});
function search(q){q=q.trim();if(!q)return;if(/^AWE-/i.test(q))return chatForPeer(q);let r=st.resources.find(x=>x.id.toLowerCase()===q.toLowerCase());if(r){view('resources');return showResource(r)}let c=st.chats.find(x=>x.id===q||x.peer.toLowerCase()===q.toLowerCase());if(c)return openChat(c.id);let ch=st.channels.find(x=>x.id.toLowerCase()===q.toLowerCase());if(ch){view('channels');toast('Channel found');return}toast('ID not known locally; connect to its owner first')}
$('#search-go')?.addEventListener('click',()=>search($('#global-search').value));$('#global-search')?.addEventListener('keydown',e=>{if(e.key==='Enter')search(e.target.value)});
$('#back-chats')?.addEventListener('click',()=>{$('#conversation-content').classList.add('hidden');$('#conversation-empty').classList.remove('hidden')});
$('#chat-menu')?.addEventListener('click',()=>$('#chat-menu-dialog').showModal());$('#chat-menu-close')?.addEventListener('click',()=>$('#chat-menu-dialog').close());
$('#rename-chat')?.addEventListener('click',()=>{const c=st.chats.find(x=>x.id===active);if(c){let n=prompt('Chat name',c.name);if(n?.trim()){c.name=n.trim();save();openChat(c.id)}}$('#chat-menu-dialog').close()});
$('#delete-chat')?.addEventListener('click',()=>{st.chats=st.chats.filter(x=>x.id!==active);active=null;save();$('#chat-menu-dialog').close();$('#conversation-content').classList.add('hidden');$('#conversation-empty').classList.remove('hidden');renderChats()});
$('#block-chat')?.addEventListener('click',()=>{const c=st.chats.find(x=>x.id===active);if(c){if(!st.blocks.includes(c.peer))st.blocks.push(c.peer);st.chats=st.chats.filter(x=>x.peer!==c.peer);st.contacts=st.contacts.filter(x=>x.uid!==c.peer);active=null;save();renderChats();renderPeople();$('#conversation-content').classList.add('hidden');$('#conversation-empty').classList.remove('hidden');toast('Blocked locally')}$('#chat-menu-dialog').close()});
$('#show-blocks')?.addEventListener('click',()=>alert(st.blocks.length?st.blocks.join('\n'):'No blocked IDs'));$('#clear-data')?.addEventListener('click',()=>{if(confirm('Delete all local data?')){localStorage.removeItem(KEY);location.reload()}});
function renderPeople(){const b=$('#people-list');if(!b)return;b.innerHTML=st.contacts.map(c=>`<article class="contact-card"><span class="avatar blue">${esc((c.name||c.uid)[0])}</span><div><strong>${esc(c.name||'AWE User')}</strong><code>${esc(c.uid)}</code></div><button class="ghost" data-open-person="${esc(c.uid)}">Chat</button></article>`).join('')||'<article class="contact-card"><div><strong>No contacts</strong><small>Use an AWE UID to start a chat.</small></div></article>';$$('[data-open-person]').forEach(e=>e.onclick=()=>chatForPeer(e.dataset.openPerson))}
function renderChannels(){const b=$('#channel-list');if(!b)return;b.innerHTML=st.channels.map(c=>`<article class="contact-card"><span class="avatar orange">📢</span><div><strong>${esc(c.name)}</strong><code>${esc(c.id)}</code><small>${c.members.length} member(s)</small></div><button class="ghost" data-channel="${c.id}">Open</button></article>`).join('')||'<article class="contact-card"><div><strong>No channels</strong><small>Create a local channel and invite peers directly.</small></div></article>';$$('[data-channel]').forEach(e=>e.onclick=()=>toast('Channel opened'))}
$('#create-channel')?.addEventListener('click',()=>{let n=prompt('Channel name');if(!n?.trim())return;let c={id:'SID-'+crypto.randomUUID().replaceAll('-','').slice(0,20).toUpperCase(),name:n.trim(),members:[st.uid],messages:[]};st.channels.unshift(c);save();renderChannels();toast('Channel created')});
async function digest(buf){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',buf))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function chooseFile(privateMode=false){const input=$('#file-input');input.onchange=async()=>{const f=input.files[0];if(!f)return;const buf=await f.arrayBuffer();const id=(privateMode?'PFID-':'FID-')+(await digest(buf)).slice(0,48).toUpperCase();let rec={id,type:privateMode?'pfid':'fid',name:f.name,size:f.size,mime:f.type,created:Date.now(),onlineOnly:true};if(privateMode){let p=prompt('Password for this private file');if(!p)return;const salt=crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveKey']);const k=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},key,{name:'AES-GCM',length:256},false,['encrypt']);const iv=crypto.getRandomValues(new Uint8Array(12));const enc=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,buf);rec={...rec,salt:Array.from(salt),iv:Array.from(iv),encrypted:true,cipherSize:enc.byteLength};await idbPut({id,blob:new Blob([enc]),meta:rec})}else await idbPut({id,blob:f,meta:rec});st.resources.unshift(rec);save();renderResources();showResource(rec);input.value=''}};input.click()}
async function chooseFolder(privateMode=false){const input=$('#folder-input');input.onchange=async()=>{const files=[...input.files];if(!files.length)return;const entries=[];for(const f of files){const b=await f.arrayBuffer();const id=await digest(b);entries.push({path:f.webkitRelativePath||f.name,size:f.size,mime:f.type,hash:id})}const base=(privateMode?'PSID-':'SID-')+await digest(new TextEncoder().encode(JSON.stringify(entries)));let rec={id:base.slice(0,60).toUpperCase(),type:privateMode?'psid':'sid',name:(files[0].webkitRelativePath||'site').split('/')[0],files:entries,created:Date.now(),onlineOnly:true};st.resources.unshift(rec);save();renderResources();showResource(rec);input.value=''}};input.click()}
$('#make-fid')?.addEventListener('click',()=>chooseFile(false));$('#make-pfid')?.addEventListener('click',()=>chooseFile(true));$('#make-sid')?.addEventListener('click',()=>chooseFolder(false));$('#make-psid')?.addEventListener('click',()=>chooseFolder(true));$('#make-cfid')?.addEventListener('click',()=>{let r=st.resources.find(x=>x.type==='fid'||x.type==='pfid');if(!r)return toast('Create a file resource first');let c={id:'CFID-'+crypto.randomUUID().replaceAll('-','').slice(0,24).toUpperCase(),type:'cfid',target:r.id,created:Date.now()};st.resources.unshift(c);save();renderResources();showResource(c)});
function renderResources(){const b=$('#resource-list');if(!b)return;b.innerHTML=st.resources.map(r=>`<article class="resource-row"><span>${r.type==='fid'?'📄':r.type==='pfid'?'🔐':r.type==='sid'?'🌐':r.type==='psid'?'🛡️':'⚡'}</span><div><strong>${esc(r.name||r.id)}</strong><code>${esc(r.id)}</code><small>${esc(r.type.toUpperCase())}</small></div><button class="ghost" data-resource="${r.id}">Details</button></article>`).join('')||'<p class="empty-small">No resources yet.</p>';$$('[data-resource]').forEach(e=>e.onclick=()=>showResource(st.resources.find(x=>x.id===e.dataset.resource)))}
function showResource(r){if(!r)return;$('#id-title').textContent=r.type.toUpperCase();$('#id-value').value=r.id;$('#id-details').textContent=JSON.stringify(r,null,2);$('#id-dialog').showModal()}
$('#id-close')?.addEventListener('click',()=>$('#id-dialog').close());$('#id-copy')?.addEventListener('click',()=>copy($('#id-value').value));
function idbPut(v){return new Promise((res,rej)=>{const q=indexedDB.open('AWEP2PAWE_FILES',1);q.onupgradeneeded=()=>q.result.createObjectStore('files',{keyPath:'id'});q.onsuccess=()=>{const d=q.result,t=d.transaction('files','readwrite');t.objectStore('files').put(v);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)};q.onerror=()=>rej(q.error)})}
async function idbGet(id){return new Promise((res,rej)=>{const q=indexedDB.open('AWEP2PAWE_FILES',1);q.onsuccess=()=>{const r=q.result.transaction('files').objectStore('files').get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)};q.onerror=()=>rej(q.error)})}
/* Direct WebRTC signaling: no application backend or storage service. */
const RTC={iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}]};
function waitIce(p){if(p.iceGatheringState==='complete')return Promise.resolve();return new Promise(r=>{let done=false;const f=()=>{if(p.iceGatheringState==='complete'&&!done){done=true;p.removeEventListener('icegatheringstatechange',f);r()}};p.addEventListener('icegatheringstatechange',f);setTimeout(()=>{if(!done){done=true;p.removeEventListener('icegatheringstatechange',f);r()}},8000)})}
function newPC(init){if(pc)pc.close();pc=new RTCPeerConnection(RTC);pc.onconnectionstatechange=()=>{$('#p2p-status').textContent=pc.connectionState};pc.ondatachannel=e=>attach(e.channel);if(init)attach(pc.createDataChannel('awe',{ordered:true}));return pc}
function attach(c){dc=c;c.binaryType='arraybuffer';c.onopen=()=>{toast('P2P connected');sendPacket({t:'hello',uid:st.uid})};c.onclose=()=>$('#p2p-status').textContent='offline';c.onmessage=e=>receive(e.data)}
function signalExport(){if(!pc?.localDescription)return;const s=btoa(JSON.stringify({v:2,uid:st.uid,type:pc.localDescription.type,sdp:pc.localDescription.sdp}));$('#signal-code').value=s;$('#signal-dialog').showModal();copy(s)}
async function makeOffer(){if(!active)return toast('Open a chat first');newPC(true);await pc.setLocalDescription(await pc.createOffer());await waitIce();signalExport()}
async function acceptSignal(raw){try{const x=JSON.parse(atob(raw.trim()));if(!x.sdp)throw Error();if(x.type==='offer'){newPC(false);await pc.setRemoteDescription({type:'offer',sdp:x.sdp});await pc.setLocalDescription(await pc.createAnswer());await waitIce();signalExport();toast('Answer ready — send it back')}else if(x.type==='answer'){if(!pc)return toast('Create an offer first');await pc.setRemoteDescription({type:'answer',sdp:x.sdp});toast('Answer accepted')}else throw Error()}catch(e){toast('Invalid connection code')}}
$('#connect')?.addEventListener('click',()=>active?makeOffer():toast('Open a chat first'));$('#signal-close')?.addEventListener('click',()=>$('#signal-dialog').close());$('#copy-signal')?.addEventListener('click',()=>copy($('#signal-code').value));$('#paste-signal')?.addEventListener('click',()=>{const x=prompt('Paste peer connection code');if(x)acceptSignal(x)});
function receive(raw){if(typeof raw!=='string')return;let m;try{m=JSON.parse(raw)}catch{return}if(m.t==='hello'){if(m.uid&&m.uid!==st.uid)chatForPeer(m.uid);return}if(m.t==='msg'){const c=st.chats.find(x=>x.peer===m.from)||chatForPeer(m.from);if(c)addMsg(c,{...m,mine:false});return}if(m.t==='file-meta'){rx.set(m.id,{meta:m,chunks:[],got:0});return}if(m.t==='file-chunk'){const x=rx.get(m.id);if(x){x.chunks[m.n]=Uint8Array.from(atob(m.data),c=>c.charCodeAt(0));x.got++;if(x.got===m.total)finishRx(m.id)}}if(m.t==='file-done')return;if(m.t==='call-offer')answerCall(m);if(m.t==='call-answer'&&window.__callPC)window.__callPC.setRemoteDescription(m.sdp);if(m.t==='candidate'&&window.__callPC)window.__callPC.addIceCandidate(m.c)}
function b64(u){let s='';const a=new Uint8Array(u);for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(s)}
async function sendFile(f){if(!dc||dc.readyState!=='open')return toast('Connect to the peer first');const id='FID-'+await digest(await f.arrayBuffer());const c=st.chats.find(x=>x.id===active);const meta={t:'file-meta',id,name:f.name,size:f.size,mime:f.type,total:Math.ceil(f.size/CHUNK)};sendPacket(meta);const buf=new Uint8Array(await f.arrayBuffer());for(let n=0;n<meta.total;n++){while(dc.bufferedAmount>2*1024*1024)await new Promise(r=>setTimeout(r,15));sendPacket({t:'file-chunk',id,n,total:meta.total,data:b64(buf.subarray(n*CHUNK,(n+1)*CHUNK))})}sendPacket({t:'file-done',id});if(c)addMsg(c,{mine:true,file:{id,name:f.name,size:f.size},ts:Date.now()});toast('File sent')}
function finishRx(id){const x=rx.get(id);if(!x)return;const blob=new Blob(x.chunks,{type:x.meta.mime||'application/octet-stream'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=x.meta.name||id;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);rx.delete(id);toast('File received')}
$('#pick-file')?.addEventListener('click',()=>{const i=$('#file-input');i.onchange=()=>{const f=i.files[0];if(f)sendFile(f);i.value=''};i.click()});
/* Calls */
async function startCall(video=false,screen=false){if(!active)return toast('Open a chat first');if(!dc||dc.readyState!=='open')return toast('Connect to the peer first');if(!navigator.mediaDevices)return toast('Media APIs unavailable');if(localStream)localStream.getTracks().forEach(t=>t.stop());localStream=screen?await navigator.mediaDevices.getDisplayMedia({video:true,audio:true}):await navigator.mediaDevices.getUserMedia({audio:true,video:video});window.__callPC=new RTCPeerConnection(RTC);localStream.getTracks().forEach(t=>window.__callPC.addTrack(t,localStream));window.__callPC.ontrack=e=>{$('#remote-video').srcObject=e.streams[0]};window.__callPC.onicecandidate=e=>{if(e.candidate)sendPacket({t:'candidate',c:e.candidate})};const o=await window.__callPC.createOffer();await window.__callPC.setLocalDescription(o);sendPacket({t:'call-offer',sdp:o});$('#call-overlay').classList.remove('hidden');$('#call-title').textContent=video?'Video call':'Voice call';$('#call-state').textContent='Calling…';$('#local-video').srcObject=localStream;$('#local-video').style.display=video?'block':'none'}
async function answerCall(m){if(!navigator.mediaDevices)return;if(localStream)localStream.getTracks().forEach(t=>t.stop());localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:true});window.__callPC=new RTCPeerConnection(RTC);localStream.getTracks().forEach(t=>window.__callPC.addTrack(t,localStream));window.__callPC.ontrack=e=>$('#remote-video').srcObject=e.streams[0];window.__callPC.onicecandidate=e=>{if(e.candidate)sendPacket({t:'candidate',c:e.candidate})};await window.__callPC.setRemoteDescription(m.sdp);const a=await window.__callPC.createAnswer();await window.__callPC.setLocalDescription(a);sendPacket({t:'call-answer',sdp:a});$('#call-overlay').classList.remove('hidden');$('#local-video').srcObject=localStream;$('#local-video').style.display='block'}
function endCall(){window.__callPC?.close();window.__callPC=null;localStream?.getTracks().forEach(t=>t.stop());localStream=null;$('#call-overlay').classList.add('hidden')}
$('#voice')?.addEventListener('click',()=>startCall(false));$('#video')?.addEventListener('click',()=>startCall(true));$('#screen')?.addEventListener('click',()=>startCall(true,true));$('#call-hangup')?.addEventListener('click',endCall);$('#call-close')?.addEventListener('click',endCall);$('#call-mute')?.addEventListener('click',()=>localStream?.getAudioTracks().forEach(t=>t.enabled=!t.enabled));$('#call-camera')?.addEventListener('click',()=>localStream?.getVideoTracks().forEach(t=>t.enabled=!t.enabled));$('#call-screen')?.addEventListener('click',async()=>{if(!localStream)return;const s=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});const sender=window.__callPC?.getSenders().find(x=>x.track?.kind==='video');if(sender&&s.getVideoTracks()[0])await sender.replaceTrack(s.getVideoTracks()[0])});
function renderCalls(){const b=$('#call-history');if(!b)return;b.innerHTML=st.calls.map(c=>`<article class="contact-card"><span>📞</span><div><strong>${esc(c.peer)}</strong><small>${new Date(c.ts).toLocaleString()}</small></div><code>${esc(c.kind)}</code></article>`).join('')||'<article class="contact-card"><div><strong>No calls</strong><small>Calls appear here after use.</small></div></article>'}
/* Language selector */
if($('#view-settings')&&!$('#language-select')){const row=document.createElement('div');row.className='setting';row.innerHTML='<div><strong>Language</strong><small>English is default. 12 languages are available.</small></div><select id="language-select">'+Object.keys(LANGS).map(x=>`<option value="${x}">${x.toUpperCase()}</option>`).join('')+'</select>';$('#view-settings .settings-panel').append(row);$('#language-select').value=st.lang;$('#language-select').onchange=e=>{st.lang=e.target.value;save();applyLang()}}
renderChats();renderPeople();renderChannels();renderResources();renderCalls();
})();
