(()=>{'use strict';
const $=s=>document.querySelector(s);const state={pc:null,dc:null,session:null,role:null,call:null,callMode:null,localStream:null,pendingCall:null};
const enc=new TextEncoder(),dec=new TextDecoder();
const toast=m=>{const e=$('#toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),2200)};
const b64=a=>{let s='';for(const b of new Uint8Array(a))s+=String.fromCharCode(b);return btoa(s).replace(/\\+/g,'-').replace(/\\//g,'_').replace(/=+$/,'')};
const ub64=s=>{s=s.replace(/-/g,'+').replace(/_/g,'/');s+='='.repeat((4-s.length%4)%4);const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a};
function qr(text){const box=$('#qr');box.innerHTML='';if(!window.qrcode)return;const q=qrcode(0,'M');q.addData(text);q.make();box.innerHTML=q.createSvgTag(6,0)}
function payload(o){return 'aweqr:'+b64(enc.encode(JSON.stringify({v:1,...o})))}
function parse(v){try{if(!v.startsWith('aweqr:'))throw 0;const o=JSON.parse(dec.decode(ub64(v.slice(6))));return o.v===1?o:null}catch{return null}}
function ice(pc){return new Promise(resolve=>{if(pc.iceGatheringState==='complete')return resolve();const t=setTimeout(resolve,3500);pc.addEventListener('icegatheringstatechange',()=>{if(pc.iceGatheringState==='complete'){clearTimeout(t);resolve()}})})}
function rtc(){return new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]})}
function showChat(){ $('#home').classList.add('hidden');$('#chat').classList.remove('hidden') }
function add(text,mine){const b=$('#messages'),e=document.createElement('div');e.className='bubble '+(mine?'mine':'');e.textContent=text;b.appendChild(e);b.scrollTop=b.scrollHeight}
function bind(){const d=state.dc;if(!d)return;d.onopen=()=>{showChat();$('#qr-status').textContent='Direct P2P connected';toast('Connected — direct P2P')};d.onclose=()=>toast('Peer disconnected');d.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.t==='msg')add(m.text,false);if(m.t==='call-offer')incomingCall(m);if(m.t==='call-answer')answerCall(m.sdp);if(m.t==='call-reject'){closeCall();toast('Call declined')}if(m.t==='call-end')closeCall();if(m.t==='call-control'&&state.call){if(m.action==='camera-off')toast('Peer camera off');if(m.action==='camera-on')toast('Peer camera on')}}catch{}}}
async function createConnection(){if(state.pc)return;state.role='offer';state.pc=rtc();state.dc=state.pc.createDataChannel('chat',{ordered:true});bind();const offer=await state.pc.createOffer();await state.pc.setLocalDescription(offer);await ice(state.pc);state.session={type:'offer',sdp:state.pc.localDescription.sdp};qr(payload(state.session));$('#qr-status').textContent='Scan this QR on the other device. Then scan its answer QR here.';toast('Connection QR ready')}
async function acceptOffer(o){if(state.pc)return;state.role='answer';state.pc=rtc();state.pc.ondatachannel=e=>{state.dc=e.channel;bind()};await state.pc.setRemoteDescription({type:'offer',sdp:o.sdp});const ans=await state.pc.createAnswer();await state.pc.setLocalDescription(ans);await ice(state.pc);state.session={type:'answer',sdp:state.pc.localDescription.sdp};qr(payload(state.session));$('#qr-status').textContent='Answer QR ready — show it to the first device';toast('Answer QR generated')}
async function acceptAnswer(o){if(!state.pc||state.role!=='offer')return toast('No pending connection');await state.pc.setRemoteDescription({type:'answer',sdp:o.sdp});$('#qr-status').textContent='Connecting directly…'}
async function decodeInput(v){const o=parse(v);if(!o)return toast('Invalid AWE QR');if(o.type==='offer')await acceptOffer(o);else if(o.type==='answer')await acceptAnswer(o);else toast('Unsupported QR')}
async function scan(){if(!navigator.mediaDevices?.getUserMedia)return toast('Camera unavailable');const d=$('#scanner'),v=$('#scan-video');d.showModal();let stream;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});v.srcObject=stream;if(!('BarcodeDetector'in window))return toast('Use QR image on this browser');const detector=new BarcodeDetector({formats:['qr_code']});const loop=async()=>{if(!d.open)return;try{const c=await detector.detect(v);if(c[0]?.rawValue){stream.getTracks().forEach(t=>t.stop());d.close();await decodeInput(c[0].rawValue);return}}catch{}requestAnimationFrame(loop)};loop()}catch{toast('Camera permission denied');d.close()}}
$('#qr-image').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const img=await createImageBitmap(f);if(!('BarcodeDetector'in window))throw 0;const d=new BarcodeDetector({formats:['qr_code']}),c=await d.detect(img);$('#scanner').close();await decodeInput(c[0]?.rawValue||'')}catch{toast('Could not read QR image')}};
async function send(text){if(!state.dc||state.dc.readyState!=='open')return toast('Connect to a peer first');state.dc.send(JSON.stringify({t:'msg',text}));add(text,true)}
async function startCall(mode){if(!state.dc||state.dc.readyState!=='open')return toast('Connect to a peer first');if(state.call)return toast('Call already active');const video=mode!=='voice';let stream;try{stream=await navigator.mediaDevices.getUserMedia({audio:true,video})}catch{return toast('Microphone/camera permission denied')};const pc=rtc();state.call={pc,stream,initiator:true,mode};stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>$('#remote').srcObject=e.streams[0];const offer=await pc.createOffer();await pc.setLocalDescription(offer);await ice(pc);state.dc.send(JSON.stringify({t:'call-offer',mode,sdp:pc.localDescription.sdp}));showCall(mode==='voice'?'Voice call':'Video call',stream);}
function incomingCall(m){if(state.call)return;state.pendingCall=m;$('#incoming-title').textContent=m.mode==='voice'?'Incoming voice call':'Incoming video call';$('#incoming').showModal()}
async function answerIncoming(accept){$('#incoming').close();const m=state.pendingCall;state.pendingCall=null;if(!accept){state.dc.send(JSON.stringify({t:'call-reject'}));return}let stream;try{stream=await navigator.mediaDevices.getUserMedia({audio:true,video:m.mode!=='voice'})}catch{return toast('Microphone/camera permission denied')};const pc=rtc();state.call={pc,stream,initiator:false,mode:m.mode};stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>$('#remote').srcObject=e.streams[0];await pc.setRemoteDescription({type:'offer',sdp:m.sdp});const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await ice(pc);state.dc.send(JSON.stringify({t:'call-answer',sdp:pc.localDescription.sdp}));showCall(m.mode==='voice'?'Voice call':'Video call',stream)}
async function answerCall(sdp){if(!state.call?.initiator)return;await state.call.pc.setRemoteDescription({type:'answer',sdp});$('#call-state').textContent='Connected'}
function showCall(title,stream){$('#call-title').textContent=title;$('#call-state').textContent='Connecting…';$('#local').srcObject=stream;$('#call').showModal()}
async function switchVideo(){if(!state.call)return;const c=state.call;const vt=c.stream.getVideoTracks()[0];if(vt){vt.enabled=!vt.enabled;$('#camera').textContent=vt.enabled?'📹 Camera on':'🚫 Camera off';state.dc?.send(JSON.stringify({t:'call-control',action:vt.enabled?'camera-on':'camera-off'}));return}try{const s=await navigator.mediaDevices.getUserMedia({video:true,audio:false}),track=s.getVideoTracks()[0];c.stream.addTrack(track);c.pc.addTrack(track,c.stream);$('#local').srcObject=c.stream;const offer=await c.pc.createOffer();await c.pc.setLocalDescription(offer);await ice(c.pc);state.dc.send(JSON.stringify({t:'call-offer',mode:'video-upgrade',sdp:c.pc.localDescription.sdp}));$('#call-title').textContent='Video call'}catch{toast('Camera unavailable')}}
function toggleMute(){const t=state.call?.stream.getAudioTracks()[0];if(!t)return;t.enabled=!t.enabled;$('#mute').textContent=t.enabled?'🎙 Mute':'🔇 Unmute'}
function closeCall(send=true){if(send&&state.dc?.readyState==='open')try{state.dc.send(JSON.stringify({t:'call-end'}))}catch{};if(state.call){state.call.stream.getTracks().forEach(t=>t.stop());state.call.pc.close();state.call=null}try{$('#call').close()}catch{} }
$('#start').onclick=createConnection;$('#show-qr').onclick=createConnection;$('#scan').onclick=scan;$('#scan-qr').onclick=scan;$('#scan-image').onclick=()=>$('#qr-image').click();$('#close-scan').onclick=()=>$('#scanner').close();$('#composer').onsubmit=e=>{e.preventDefault();const i=$('#message');if(i.value.trim()){send(i.value.trim());i.value=''}};$('#voice').onclick=()=>startCall('voice');$('#video').onclick=()=>startCall('video');$('#screen').onclick=async()=>{if(!state.call)return toast('Start a call first');try{const s=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true}),old=state.call.stream.getVideoTracks()[0],nt=s.getVideoTracks()[0];const sender=state.call.pc.getSenders().find(x=>x.track?.kind==='video');if(sender)await sender.replaceTrack(nt);if(old)old.stop();state.call.stream=s;$('#local').srcObject=s;s.getVideoTracks()[0].onended=()=>toast('Screen sharing stopped')}catch{toast('Screen sharing cancelled')}};$('#close-call').onclick=()=>closeCall();$('#hangup').onclick=()=>closeCall();$('#mute').onclick=toggleMute;$('#camera').onclick=switchVideo;$('#accept-call').onclick=()=>answerIncoming(true);$('#reject-call').onclick=()=>answerIncoming(false);$('#back').onclick=()=>{$('#chat').classList.add('hidden');$('#home').classList.remove('hidden')};
addEventListener('beforeunload',()=>{try{closeCall(false);state.dc?.close();state.pc?.close()}catch{}},{once:true});
})();