(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STATE='AWEP2PAWE_STATE_V11', DB='AWEP2PAWE_DB', STORE='blobs', CHUNK=48*1024;
const LANG={en:['Chats','People','Channels','Resources','Calls','Settings','Search UID, FID, PFID, SID, PSID or CFID…','New chat','Write a message…'],hy:['Չատեր','Մարդիկ','Ալիքներ','Ռեսուրսներ','Զանգեր','Կարգավորումներ','Որոնել UID, FID, PFID, SID, PSID կամ CFID…','Նոր չատ','Գրել հաղորդագրություն…'],ru:['Чаты','Люди','Каналы','Ресурсы','Звонки','Настройки','Поиск UID, FID, PFID, SID, PSID или CFID…','Новый чат','Сообщение…'],es:['Chats','Personas','Canales','Recursos','Llamadas','Ajustes','Buscar UID, FID, PFID, SID, PSID o CFID…','Nuevo chat','Escribe un mensaje…'],fr:['Discussions','Personnes','Canaux','Ressources','Appels','Réglages','Rechercher UID, FID, PFID, SID, PSID ou CFID…','Nouvelle discussion','Écrire un message…'],de:['Chats','Personen','Kanäle','Ressourcen','Anrufe','Einstellungen','UID, FID, PFID, SID, PSID oder CFID suchen…','Neuer Chat','Nachricht schreiben…'],pt:['Chats','Pessoas','Canais','Recursos','Chamadas','Definições','Pesquisar UID, FID, PFID, SID, PSID ou CFID…','Novo chat','Escreva uma mensagem…'],ar:['المحادثات','الأشخاص','القنوات','الموارد','المكالمات','الإعدادات','ابحث عن UID أو FID أو PFID أو SID أو PSID أو CFID…','محادثة جديدة','اكتب رسالة…'],hi:['चैट','लोग','चैनल','संसाधन','कॉल','सेटिंग्स','UID, FID, PFID, SID, PSID या CFID खोजें…','नई चैट','संदेश लिखें…'],zh:['聊天','联系人','频道','资源','通话','设置','搜索 UID、FID、PFID、SID、PSID 或 CFID…','新聊天','输入消息…'],tr:['Sohbetler','Kişiler','Kanallar','Kaynaklar','Aramalar','Ayarlar','UID, FID, PFID, SID, PSID veya CFID ara…','Yeni sohbet','Mesaj yaz…'],fa:['گفتگوها','افراد','کانال‌ها','منابع','تماس‌ها','تنظیمات','جستجوی UID، FID، PFID، SID، PSID یا CFID…','گفتگوی جدید','پیام بنویسید…']};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=t=>{const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__aweToast);window.__aweToast=setTimeout(()=>e.classList.remove('show'),2200)};
const copy=async v=>{try{await navigator.clipboard.writeText(v);toast('Copied')}catch{prompt('Copy',v)}};
const load=()=>{try{return JSON.parse(localStorage.getItem(STATE)||'{}')}catch{return {}}};
let st=load();st.chats||=[];st.contacts||=[];st.channels||=[];st.resources||=[];st.blocks||=[];st.calls||=[];st.lang||='en';st.theme||='light';
const save=()=>localStorage.setItem(STATE,JSON.stringify(st));
function b64(u){let s='';const a=new Uint8Array(u);for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(s)}
function ub64(s){const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a}
async function sha(data){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',data))].map(x=>x.toString(16).padStart(2,'0')).join('')}
function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>q.result.createObjectStore(STORE,{keyPath:'id'});q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function putBlob(v){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(v);t.oncomplete=()=>{d.close();res()};t.onerror=()=>{d.close();rej(t.error)}})}
async function derivePrivate(password,salt){const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function initIdentity(){if(st.identity?.publicKey&&st.identity?.privateKey&&st.uid)return;const kp=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveKey','deriveBits']);const pub=await crypto.subtle.exportKey('jwk',kp.publicKey),priv=await crypto.subtle.exportKey('jwk',kp.privateKey);st.identity={publicKey:pub,privateKey:priv};st.uid='AWE-'+(await sha(new TextEncoder().encode(JSON.stringify(pub)))).slice(0,32).toUpperCase();save()}
async function importIdentity(){const i=st.identity;return {publicKey:await crypto.subtle.importKey('jwk',i.publicKey,{name:'ECDH',namedCurve:'P-256'},true,[]),privateKey:await crypto.subtle.importKey('jwk',i.privateKey,{name:'ECDH',namedCurve:'P-256'},false,['deriveKey','deriveBits'])}}
async function makeSession(peerJwk){const me=await importIdentity(),peer=await crypto.subtle.importKey('jwk',peerJwk,{name:'ECDH',namedCurve:'P-256'},true,[]);return crypto.subtle.deriveKey({name:'ECDH',public:peer},me.privateKey,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
let active=null,pc=null,dc=null,localStream=null,callPC=null,sessionKey=null,rx=new Map();
async function encrypt(o){if(!sessionKey)return JSON.stringify(o);const iv=crypto.getRandomValues(new Uint8Array(12));const ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},sessionKey,new TextEncoder().encode(JSON.stringify(o)));return JSON.stringify({t:'enc',iv:b64(iv),d:b64(ct)})}
async function decrypt(raw){let o;try{o=JSON.parse(raw)}catch{return null}if(o?.t!=='enc')return o;if(!sessionKey)return null;try{const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:ub64(o.iv)},sessionKey,ub64(o.d));return JSON.parse(new TextDecoder().decode(pt))}catch{return null}}
async function send(o){if(dc?.readyState==='open')dc.send(await encrypt(o))}
function applyLang(){const l=LANG[st.lang]||LANG.en;document.documentElement.lang=st.lang;['chats','contacts','channels','resources','calls','settings'].forEach((n,i)=>$$(`[data-view="${n}"] span`).forEach(e=>e.textContent=l[i]));if($('#global-search'))$('#global-search').placeholder=l[6];if($('#message-input'))$('#message-input').placeholder=l[8];if($('#new-chat'))$('#new-chat').textContent='＋ '+l[7]}
function view(v){$$('.view').forEach(e=>e.classList.toggle('active-view',e.id==='view-'+v));$$('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view===v));if(v==='chats')renderChats();if(v==='contacts')renderPeople();if(v==='channels')renderChannels();if(v==='resources')renderResources();if(v==='calls')renderCalls()}
$$('[data-view]').forEach(e=>e.onclick=()=>view(e.dataset.view));
function chatForPeer(uid,name){uid=uid.trim().toUpperCase();if(!/^AWE-[A-Z0-9]{8,64}$/.test(uid))return toast('Invalid AWE UID');if(uid===st.uid)return toast('This is your UID');if(st.blocks.includes(uid))return toast('Blocked UID');let c=st.chats.find(x=>x.peer===uid&&x.type==='direct');if(!c){c={id:crypto.randomUUID(),peer:uid,name:name||uid,type:'direct',messages:[],unread:0,last:'New conversation',updated:Date.now(),verified:false};st.chats.unshift(c);if(!st.contacts.some(x=>x.uid===uid))st.contacts.unshift({uid,name:name||uid});save()}openChat(c.id);return c}
function openChat(id){const c=st.chats.find(x=>x.id===id);if(!c||st.blocks.includes(c.peer))return;active=id;c.unread=0;save();$('#conversation-empty').classList.add('hidden');$('#conversation-content').classList.remove('hidden');$('#conversation-name').textContent=c.name||c.peer;$('#conversation-avatar').textContent=(c.name||c.peer)[0]?.toUpperCase()||'A';$('#p2p-status').textContent=dc?.readyState==='open'?'connected':'offline';renderChats();renderMessages()}
function renderChats(){const b=$('#chat-items');if(!b)return;const f=document.querySelector('.filter.active')?.dataset.filter||'all';const a=st.chats.filter(c=>f==='all'||(f==='unread'&&c.unread)||(f==='groups'&&(c.type==='group'||c.type==='channel'))).sort((x,y)=>(y.updated||0)-(x.updated||0));b.innerHTML=a.map(c=>`<button class="chat-row ${c.id===active?'selected':''}" data-chat="${esc(c.id)}"><span class="avatar purple">${esc((c.name||c.peer||'A')[0].toUpperCase())}</span><span class="chat-meta"><strong>${esc(c.name||c.peer)}</strong><small>${esc(c.last||'')}</small></span>${c.unread?`<b class="unread-dot">${Math.min(99,c.unread)}</b>`:''}</button>`).join('');if($('#chat-empty'))$('#chat-empty').style.display=a.length?'none':'flex';$$('[data-chat]').forEach(e=>e.onclick=()=>openChat(e.dataset.chat))}
function renderMessages(){const c=st.chats.find(x=>x.id===active),b=$('#messages');if(!b)return;b.innerHTML=(c?.messages||[]).map(m=>`<div class="bubble-row ${m.mine?'mine':''}"><div class="bubble ${m.mine?'mine':''}">${m.file?`📎 <strong>${esc(m.file.name)}</strong><small>${esc(m.file.id)} · ${Math.ceil(m.file.size/1024)} KB</small>`:esc(m.text||'')}<time>${new Date(m.ts).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time></div></div>`).join('');b.scrollTop=b.scrollHeight}
function addMsg(c,m){c.messages.push(m);c.last=m.file?'📎 '+m.file.name:(m.text||'');c.updated=Date.now();save();renderMessages();renderChats()}
async function sendText(t){const c=st.chats.find(x=>x.id===active);if(!c||st.blocks.includes(c.peer))return;const m={t:'msg',id:crypto.randomUUID(),text:t,ts:Date.now(),from:st.uid};addMsg(c,{...m,mine:true});await send(m)}
$('#message-form')?.addEventListener('submit',e=>{e.preventDefault();const i=$('#message-input'),t=i.value.trim();if(t){sendText(t);i.value=''}});$$('.filter').forEach(e=>e.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));e.classList.add('active');renderChats()});
$('#new-chat')?.addEventListener('click',()=>{const x=prompt('AWE UID');if(x)chatForPeer(x)});$('#new-chat-2')?.addEventListener('click',()=>{const x=prompt('AWE UID');if(x)chatForPeer(x)});
function search(q){q=q.trim();if(!q)return;if(/^AWE-/i.test(q))return chatForPeer(q);const r=st.resources.find(x=>x.id.toLowerCase()===q.toLowerCase());if(r){view('resources');return showResource(r)}const c=st.chats.find(x=>x.id===q||x.peer?.toLowerCase()===q.toLowerCase());if(c)return openChat(c.id);const ch=st.channels.find(x=>x.id.toLowerCase()===q.toLowerCase());if(ch){view('channels');toast('Channel found');return}toast('ID is not available on this device')}
$('#search-go')?.addEventListener('click',()=>search($('#global-search').value));$('#global-search')?.addEventListener('keydown',e=>{if(e.key==='Enter')search(e.target.value)});$('#back-chats')?.addEventListener('click',()=>{$('#conversation-content').classList.add('hidden');$('#conversation-empty').classList.remove('hidden')});
$('#chat-menu')?.addEventListener('click',()=>$('#chat-menu-dialog').showModal());$('#chat-menu-close')?.addEventListener('click',()=>$('#chat-menu-dialog').close());$('#rename-chat')?.addEventListener('click',()=>{const c=st.chats.find(x=>x.id===active);if(c){const n=prompt('Chat name',c.name);if(n?.trim()){c.name=n.trim();save();openChat(c.id)}}$('#chat-menu-dialog').close()});$('#delete-chat')?.addEventListener('click',()=>{st.chats=st.chats.filter(x=>x.id!==active);active=null;save();$('#chat-menu-dialog').close();$('#conversation-content').classList.add('hidden');$('#conversation-empty').classList.remove('hidden');renderChats()});$('#block-chat')?.addEventListener('click',()=>{const c=st.chats.find(x=>x.id===active);if(c){if(!st.blocks.includes(c.peer))st.blocks.push(c.peer);st.chats=st.chats.filter(x=>x.peer!==c.peer);st.contacts=st.contacts.filter(x=>x.uid!==c.peer);active=null;save();renderChats();renderPeople();$('#conversation-content').classList.add('hidden');$('#conversation-empty').classList.remove('hidden');toast('Blocked locally')}$('#chat-menu-dialog').close()});$('#show-blocks')?.addEventListener('click',()=>alert(st.blocks.length?st.blocks.join('\n'):'No blocked IDs'));$('#clear-data')?.addEventListener('click',()=>{if(confirm('Delete all local data?')){localStorage.removeItem(STATE);location.reload()}});
function renderPeople(){const b=$('#people-list');if(!b)return;b.innerHTML=st.contacts.map(c=>`<article class="contact-card"><span class="avatar blue">${esc((c.name||c.uid)[0])}</span><div><strong>${esc(c.name||'AWE User')}</strong><code>${esc(c.uid)}</code></div><button class="ghost" data-open-person="${esc(c.uid)}">Chat</button></article>`).join('')||'<article class="contact-card"><div><strong>No contacts</strong><small>Use an AWE UID to start a chat.</small></div></article>';$$('[data-open-person]').forEach(e=>e.onclick=()=>chatForPeer(e.dataset.openPerson))}
function renderChannels(){const b=$('#channel-list');if(!b)return;b.innerHTML=st.channels.map(c=>`<article class="contact-card"><span class="avatar orange">📢</span><div><strong>${esc(c.name)}</strong><code>${esc(c.id)}</code><small>${c.members?.length||0} member(s)</small></div><button class="ghost" data-channel="${esc(c.id)}">Open</button></article>`).join('')||'<article class="contact-card"><div><strong>No channels</strong><small>Create a local channel and invite peers directly.</small></div></article>';$$('[data-channel]').forEach(e=>e.onclick=()=>toast('Channel opened'))}
$('#create-channel')?.addEventListener('click',()=>{const n=prompt('Channel name');if(!n?.trim())return;const c={id:'CHID-'+crypto.randomUUID().replaceAll('-','').slice(0,24).toUpperCase(),name:n.trim(),members:[st.uid],messages:[],owner:st.uid};st.channels.unshift(c);save();renderChannels();toast('Channel created')});
async function chooseFile(privateMode=false){const input=$('#file-input');input.onchange=async()=>{try{const f=input.files[0];if(!f)return;const buf=await f.arrayBuffer(),digest=await sha(buf),id=(privateMode?'PFID-':'FID-')+digest.toUpperCase();let rec={id,type:privateMode?'pfid':'fid',name:f.name,size:f.size,mime:f.type,created:Date.now(),onlineOnly:true,sha256:digest};if(privateMode){const p=prompt('Password for this private file');if(!p)return;const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derivePrivate(p,salt),enc=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,buf);rec={...rec,salt:b64(salt),iv:b64(iv),encrypted:true,cipherSha256:await sha(enc)};await putBlob({id,blob:new Blob([enc]),meta:rec})}else await putBlob({id,blob:f,meta:rec});st.resources.unshift(rec);save();renderResources();showResource(rec)}catch(e){console.error(e);toast('File creation failed')}finally{input.value=''}};input.click()}
async function chooseFolder(privateMode=false){const input=$('#folder-input');input.onchange=async()=>{try{const files=[...input.files];if(!files.length)return;const entries=[];for(const f of files){const buf=await f.arrayBuffer();entries.push({path:f.webkitRelativePath||f.name,size:f.size,mime:f.type,hash:await sha(buf)})}const manifest=JSON.stringify(entries),root=await sha(new TextEncoder().encode(manifest)),id=(privateMode?'PSID-':'SID-')+root.toUpperCase(),rec={id,type:privateMode?'psid':'sid',name:(files[0].webkitRelativePath||'site').split('/')[0],files:entries,manifestHash:root,created:Date.now(),onlineOnly:true};if(privateMode){const p=prompt('Password for this private website');if(!p)return;const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derivePrivate(p,salt),enc=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(manifest));rec.salt=b64(salt);rec.iv=b64(iv);rec.encrypted=true;await putBlob({id,blob:new Blob([enc]),meta:rec})}else await putBlob({id,blob:files.map(f=>({path:f.webkitRelativePath||f.name,blob:f})),meta:rec});st.resources.unshift(rec);save();renderResources();showResource(rec)}catch(e){console.error(e);toast('Folder creation failed')}finally{input.value=''}};input.click()}
$('#make-fid')?.addEventListener('click',()=>chooseFile(false));$('#make-pfid')?.addEventListener('click',()=>chooseFile(true));$('#make-sid')?.addEventListener('click',()=>chooseFolder(false));$('#make-psid')?.addEventListener('click',()=>chooseFolder(true));$('#make-cfid')?.addEventListener('click',()=>{const r=st.resources.find(x=>['fid','pfid','sid','psid'].includes(x.type));if(!r)return toast('Create a resource first');const c={id:'CFID-'+crypto.randomUUID().replaceAll('-','').slice(0,24).toUpperCase(),type:'cfid',target:r.id,owner:st.uid,created:Date.now()};st.resources.unshift(c);save();renderResources();showResource(c)});
function renderResources(){const b=$('#resource-list');if(!b)return;b.innerHTML=st.resources.map(r=>`<article class="resource-row"><span>${r.type==='fid'?'📄':r.type==='pfid'?'🔐':r.type==='sid'?'🌐':r.type==='psid'?'🛡️':'⚡'}</span><div><strong>${esc(r.name||r.id)}</strong><code>${esc(r.id)}</code><small>${esc(r.type.toUpperCase())}</small></div><button class="ghost" data-resource="${esc(r.id)}">Details</button></article>`).join('')||'<p class="empty-small">No resources yet.</p>';$$('[data-resource]').forEach(e=>e.onclick=()=>showResource(st.resources.find(x=>x.id===e.dataset.resource)))}
function showResource(r){if(!r)return;$('#id-title').textContent=r.type.toUpperCase();$('#id-value').value=r.id;$('#id-details').textContent=JSON.stringify(r,null,2);$('#id-dialog').showModal()}
$('#id-close')?.addEventListener('click',()=>$('#id-dialog').close());$('#id-copy')?.addEventListener('click',()=>copy($('#id-value').value));
const RTC={iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}],bundlePolicy:'max-bundle'};
function waitIce(p){if(p.iceGatheringState==='complete')return Promise.resolve();return new Promise(r=>{let done=false,finish=()=>{if(done)return;done=true;p.removeEventListener('icegatheringstatechange',finish);r()};p.addEventListener('icegatheringstatechange',finish);setTimeout(finish,8000)})}
function newPC(offerer){if(pc)pc.close();pc=new RTCPeerConnection(RTC);pc.onconnectionstatechange=()=>{$('#p2p-status').textContent=pc.connectionState;if(pc.connectionState==='connected')toast('P2P connected')};pc.ondatachannel=e=>attach(e.channel);if(offerer)attach(pc.createDataChannel('awe-data',{ordered:true})) ;return pc}
function attach(c){dc=c;c.binaryType='arraybuffer';c.onopen=async()=>{await send({t:'hello',uid:st.uid,pub:st.identity.publicKey});$('#p2p-status').textContent='connected'};c.onclose=()=>{$('#p2p-status').textContent='offline';sessionKey=null};c.onmessage=async e=>{const m=await decrypt(e.data);if(m)await receive(m)}}
function signalExport(){if(!pc?.localDescription)return;$('#signal-code').value=btoa(JSON.stringify({v:3,uid:st.uid,pub:st.identity.publicKey,type:pc.localDescription.type,sdp:pc.localDescription.sdp}));$('#signal-dialog').showModal()}
async function makeOffer(){if(!active)return toast('Open a chat first');newPC(true);await pc.setLocalDescription(await pc.createOffer());await waitIce(pc);signalExport()}
async function acceptSignal(raw){try{const x=JSON.parse(atob(raw.trim()));if(!x.sdp||!x.pub)throw Error();if(x.uid)chatForPeer(x.uid);if(x.type==='offer'){newPC(false);await pc.setRemoteDescription({type:'offer',sdp:x.sdp});sessionKey=await makeSession(x.pub);await pc.setLocalDescription(await pc.createAnswer());await waitIce(pc);signalExport();toast('Answer ready — send it back')}else if(x.type==='answer'){if(!pc)throw Error();sessionKey=await makeSession(x.pub);await pc.setRemoteDescription({type:'answer',sdp:x.sdp});toast('Answer accepted')}else throw Error()}catch(e){console.error(e);toast('Invalid connection code')}}
$('#connect')?.addEventListener('click',()=>active?makeOffer():toast('Open a chat first'));$('#signal-close')?.addEventListener('click',()=>$('#signal-dialog').close());$('#copy-signal')?.addEventListener('click',()=>copy($('#signal-code').value));$('#paste-signal')?.addEventListener('click',()=>{const x=prompt('Paste peer connection code');if(x)acceptSignal(x)});
async function receive(m){if(m.t==='hello'){if(m.pub)sessionKey=await makeSession(m.pub);return}if(m.t==='msg'){const c=st.chats.find(x=>x.peer===m.from)||chatForPeer(m.from);if(c)addMsg(c,{...m,mine:false});return}if(m.t==='file-meta'){rx.set(m.id,{meta:m,chunks:new Array(m.total),got:0});return}if(m.t==='file-chunk'){const x=rx.get(m.id);if(!x)return;x.chunks[m.n]=ub64(m.data);x.got++;if(x.got===x.meta.total)await finishRx(m.id)}if(m.t==='call-offer')await answerCall(m);if(m.t==='call-answer'&&callPC)await callPC.setRemoteDescription(m.sdp);if(m.t==='candidate'&&callPC)try{await callPC.addIceCandidate(m.c)}catch{}}
async function sendFile(f){if(dc?.readyState!=='open')return toast('Connect to the peer first');const buf=new Uint8Array(await f.arrayBuffer()),hash=await sha(buf),id='FID-'+hash.toUpperCase(),c=st.chats.find(x=>x.id===active),total=Math.ceil(buf.length/CHUNK);await send({t:'file-meta',id,name:f.name,size:f.size,mime:f.type,total,sha256:hash});for(let n=0;n<total;n++){while(dc.bufferedAmount>2*1024*1024)await new Promise(r=>setTimeout(r,20));await send({t:'file-chunk',id,n,total,data:b64(buf.subarray(n*CHUNK,(n+1)*CHUNK))})}if(c)addMsg(c,{mine:true,file:{id,name:f.name,size:f.size},ts:Date.now()});toast('File sent')}
async function finishRx(id){const x=rx.get(id);if(!x)return;const blob=new Blob(x.chunks,{type:x.meta.mime||'application/octet-stream'}),buf=await blob.arrayBuffer(),actual=await sha(buf);if(actual!==x.meta.sha256){rx.delete(id);return toast('File integrity check failed')}await putBlob({id,blob,meta:{name:x.meta.name,size:x.meta.size,mime:x.meta.mime,sha256:actual}});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=x.meta.name||id;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);rx.delete(id);toast('File received and verified')}
$('#pick-file')?.addEventListener('click',()=>{const i=$('#file-input');i.onchange=()=>{const f=i.files[0];if(f)sendFile(f);i.value=''};i.click()});
async function startCall(video=false,screen=false){if(!active||dc?.readyState!=='open')return toast('Connect to the peer first');if(!navigator.mediaDevices)return toast('Media APIs unavailable');localStream?.getTracks().forEach(t=>t.stop());localStream=screen?await navigator.mediaDevices.getDisplayMedia({video:true,audio:true}):await navigator.mediaDevices.getUserMedia({audio:true,video});callPC=new RTCPeerConnection(RTC);localStream.getTracks().forEach(t=>callPC.addTrack(t,localStream));callPC.ontrack=e=>{$('#remote-video').srcObject=e.streams[0]};callPC.onicecandidate=e=>{if(e.candidate)send({t:'candidate',c:e.candidate})};await callPC.setLocalDescription(await callPC.createOffer());await waitIce(callPC);await send({t:'call-offer',sdp:callPC.localDescription,video,screen});$('#call-overlay').classList.remove('hidden');$('#call-title').textContent=screen?'Screen sharing':video?'Video call':'Voice call';$('#call-state').textContent='Calling…';$('#local-video').srcObject=localStream;$('#local-video').style.display=video||screen?'block':'none'}
async function answerCall(m){if(!navigator.mediaDevices)return;localStream?.getTracks().forEach(t=>t.stop());localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:!!m.video});callPC=new RTCPeerConnection(RTC);localStream.getTracks().forEach(t=>callPC.addTrack(t,localStream));callPC.ontrack=e=>{$('#remote-video').srcObject=e.streams[0]};callPC.onicecandidate=e=>{if(e.candidate)send({t:'candidate',c:e.candidate})};await callPC.setRemoteDescription(m.sdp);await callPC.setLocalDescription(await callPC.createAnswer());await waitIce(callPC);await send({t:'call-answer',sdp:callPC.localDescription});$('#call-overlay').classList.remove('hidden');$('#call-title').textContent=m.video?'Video call':'Voice call';$('#call-state').textContent='Connected';$('#local-video').srcObject=localStream;$('#local-video').style.display=m.video?'block':'none'}
function endCall(){callPC?.close();callPC=null;localStream?.getTracks().forEach(t=>t.stop());localStream=null;$('#call-overlay')?.classList.add('hidden')}
$('#voice')?.addEventListener('click',()=>startCall(false));$('#video')?.addEventListener('click',()=>startCall(true));$('#screen')?.addEventListener('click',()=>startCall(true,true));$('#call-hangup')?.addEventListener('click',endCall);$('#call-close')?.addEventListener('click',endCall);$('#call-mute')?.addEventListener('click',()=>localStream?.getAudioTracks().forEach(t=>t.enabled=!t.enabled));$('#call-camera')?.addEventListener('click',()=>localStream?.getVideoTracks().forEach(t=>t.enabled=!t.enabled));$('#call-screen')?.addEventListener('click',async()=>{if(!callPC)return;const s=await navigator.mediaDevices.getDisplayMedia({video:true});const sender=callPC.getSenders().find(x=>x.track?.kind==='video');if(sender)await sender.replaceTrack(s.getVideoTracks()[0])});
function renderCalls(){const b=$('#call-history');if(!b)return;b.innerHTML=st.calls.map(c=>`<article class="contact-card"><span>📞</span><div><strong>${esc(c.peer)}</strong><small>${new Date(c.ts).toLocaleString()}</small></div><code>${esc(c.kind)}</code></article>`).join('')||'<article class="contact-card"><div><strong>No calls</strong><small>Calls appear here after use.</small></div></article>'}
if($('#view-settings')&&!$('#language-select')){const row=document.createElement('div');row.className='setting';row.innerHTML='<div><strong>Language</strong><small>English is default. 12 languages are available.</small></div><select id="language-select">'+Object.keys(LANG).map(x=>`<option value="${x}">${x.toUpperCase()}</option>`).join('')+'</select>';$('#view-settings .settings-panel').append(row);$('#language-select').value=st.lang;$('#language-select').onchange=e=>{st.lang=e.target.value;save();applyLang()}}
$('#theme-light')?.addEventListener('click',()=>{st.theme='light';document.body.className='light';save()});$('#theme-dark')?.addEventListener('click',()=>{st.theme='dark';document.body.className='dark';save()});$('#copy-uid')?.addEventListener('click',()=>copy(st.uid));$('#copy-uid-2')?.addEventListener('click',()=>copy(st.uid));
(async()=>{try{await initIdentity();$('#identity-id').textContent=st.uid;$('#settings-id').textContent=st.uid;document.body.className=st.theme;applyLang();renderChats();renderPeople();renderChannels();renderResources();renderCalls()}catch(e){console.error(e);toast('Initialization failed')}})();
})();