(()=>{'use strict';
const KEY='AWEP2PAWE_STATE_V11';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const toast=m=>{const e=document.querySelector('#toast');if(e){e.textContent=m;e.classList.add('show');clearTimeout(window.__aweSidToast);window.__aweSidToast=setTimeout(()=>e.classList.remove('show'),2200)}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mime=n=>({html:'text/html',htm:'text/html',css:'text/css',js:'text/javascript',mjs:'text/javascript',json:'application/json',wasm:'application/wasm',svg:'image/svg+xml',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',ico:'image/x-icon',txt:'text/plain'})[(String(n).split('.').pop()||'').toLowerCase()]||'application/octet-stream';
const sidOf=r=>r?.id&&/^(SID|PSID)-/.test(r.id)?r.id:null;
async function localFiles(id,password){if(!window.AWEResources)throw Error('Resource engine unavailable');return window.AWEResources.read(id,password)}
function pathJoin(base,path){const parts=(String(base||'').replace(/^\/|\/$/g,'')+'/'+String(path||'').replace(/^\//,'')).split('/');const out=[];for(const p of parts){if(!p||p==='.')continue;if(p==='..'){out.pop();continue}out.push(p)}return out.join('/')}
async function buildSite(id,password){const files=await localFiles(id,password);const map=new Map(files.map(f=>[String(f.name).replace(/\\/g,'/'),f]));const entry=map.get('index.html')||map.get('index.htm');if(!entry)throw Error('SID requires index.html');let html=await entry.blob.text();const token=location.origin+location.pathname+'?sid='+encodeURIComponent(id);const base=document.createElement('base');base.href=token;html=html.replace(/<head([^>]*)>/i,'<head$1>'+base.outerHTML);const blob=new Blob([html],{type:'text/html;charset=utf-8'});return {files,map,entry,blob}}
async function openLocal(id,password){const site=await buildSite(id,password);const url=URL.createObjectURL(site.blob);const w=window.open(url,'_blank','noopener,noreferrer');if(!w){const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.click()}setTimeout(()=>URL.revokeObjectURL(url),60000);return site}
function requestPeer(resourceId,path){const request={kind:'resource-request',version:1,resourceId,path:path||'index.html',requestId:crypto.randomUUID(),accept:'bytes',maxBytes:1024*1024};if(typeof window.__aweSendControl!=='function')throw Error('No authenticated P2P transport is connected');window.__aweSendControl(request);return request.requestId}
function announceResource(r){if(!sidOf(r))throw Error('Not an SID resource');return {kind:'resource-announce',version:1,resourceId:r.id,resourceKind:r.kind,owner:r.owner||load().uid||null,integrity:r.hash,files:(r.files||[]).map(f=>({name:f.name,size:f.size,type:f.type,hash:f.hash}))}}
function installProtocol(){window.AWESID={openLocal,requestPeer,announceResource,buildSite};window.dispatchEvent(new CustomEvent('awe:sid-ready'));document.addEventListener('click',async e=>{const b=e.target.closest('[data-sid-open]');if(!b)return;try{const r=(load().resources||[]).find(x=>x.id===b.dataset.sidOpen);if(!r)return toast('SID not found locally');let pw=null;if(r.kind==='PSID')pw=prompt('Password');await openLocal(r.id,pw)}catch(err){toast(err.message||'SID open failed')}})}
function addResourceActions(){const box=document.querySelector('#resource-list');if(!box||box.dataset.sidBound)return;box.dataset.sidBound='1';const obs=new MutationObserver(()=>{box.querySelectorAll('[data-resource-id]').forEach(card=>{if(card.dataset.sidDecorated)return;card.dataset.sidDecorated='1';const id=card.dataset.resourceId,r=(load().resources||[]).find(x=>x.id===id);if(!sidOf(r))return;const row=document.createElement('div');row.className='sid-actions';row.innerHTML='<button class="ghost" data-sid-open="'+esc(id)+'">Open site</button><button class="ghost" data-sid-share="'+esc(id)+'">P2P reference</button>';card.appendChild(row)})});obs.observe(box,{childList:true,subtree:true})}
installProtocol();addEventListener('load',()=>setTimeout(addResourceActions,400));
})();
